import type { KnownServiceKey } from './service-system.js'

export interface ServiceVoiceContract {
  serviceKey: KnownServiceKey
  serviceTitle: string
  promise: string
  userQuestion: string
  emotionalState: string
  conversationMode: string
  relationshipDistance: string
  directness: 'low' | 'medium' | 'high'
  warmth: 'low' | 'medium' | 'high'
  spice: 'low' | 'medium' | 'high'
  teaserJob: string
  reportJob: string
  requiredScenes: string[]
  decisionCriteria: string[]
  holdConditions: string[]
  forbiddenCustomerCopy: string[]
}

export const SERVICE_VOICE_CONTRACTS: Record<KnownServiceKey, ServiceVoiceContract> = {
  today_fortune: {
    serviceKey: 'today_fortune',
    serviceTitle: '오늘운',
    promise: '오늘 하루의 리듬을 한눈에 잡고, 무리할 일과 밀어도 되는 일을 구분하게 한다.',
    userQuestion: '오늘은 뭘 조심하고, 어디에 힘을 써야 할까?',
    emotionalState: '아침에 빠르게 방향을 확인하고 싶은 상태',
    conversationMode: '짧고 선명한 데일리 코칭',
    relationshipDistance: '옆에서 오늘 일정표를 같이 봐주는 거리',
    directness: 'high',
    warmth: 'medium',
    spice: 'medium',
    teaserJob: '오늘의 핵심 기운과 바로 써먹을 선택 기준을 먼저 준다.',
    reportJob: '일·관계·돈·컨디션을 오늘 실제 행동 단위로 나누어 말한다.',
    requiredScenes: ['출근 전 판단', '오후 집중력 저하', '메시지·약속 응답'],
    decisionCriteria: ['오늘 밀어붙일 일', '미룰 일', '말을 줄일 순간'],
    holdConditions: ['건강 이상 신호', '법률·투자 확정 판단', '상대 마음 단정'],
    forbiddenCustomerCopy: ['오늘은 모든 일이 잘 풀립니다', '반드시 성사됩니다', '운이 나쁘니 움직이지 마세요'],
  },
  lucky_color: {
    serviceKey: 'lucky_color',
    serviceTitle: '색과 물건',
    promise: '나에게 필요한 기운을 색·물건·공간의 작은 선택으로 체감하게 한다.',
    userQuestion: '오늘 또는 이번 기간에 어떤 색과 물건이 나한테 힘이 될까?',
    emotionalState: '가볍게 시작하지만 내 취향과 이유를 알고 싶은 상태',
    conversationMode: '실용적인 스타일 큐레이션',
    relationshipDistance: '옷장 앞에서 같이 골라주는 거리',
    directness: 'medium',
    warmth: 'high',
    spice: 'low',
    teaserJob: '어울리는 색 하나와 피해야 할 과한 선택 하나를 이유 있게 보여준다.',
    reportJob: '색·소재·착용 장소·업무/관계 장면별 활용법으로 확장한다.',
    requiredScenes: ['옷 고르는 순간', '회의·약속 전 준비', '책상·가방 속 물건'],
    decisionCriteria: ['기운을 보완하는 색', '과해지는 색', '오늘 쓸 물건'],
    holdConditions: ['치료·재물 보장', '가격 높은 구매 유도', '색 하나로 성격 단정'],
    forbiddenCustomerCopy: ['이 색을 사야 운이 열립니다', '비싼 물건일수록 효과가 큽니다', '색만 바꾸면 해결됩니다'],
  },
  saju_master: {
    serviceKey: 'saju_master',
    serviceTitle: '천명사주',
    promise: '명식 전체를 생활 언어로 풀어 내가 반복해 온 패턴과 다음 선택을 보게 한다.',
    userQuestion: '내 사주는 어떤 구조이고, 지금 나는 무엇을 붙잡아야 할까?',
    emotionalState: '깊은 자기 이해와 큰 방향이 필요한 상태',
    conversationMode: '도사형 해설이지만 근거는 차분히 풀어주는 방식',
    relationshipDistance: '오래 본 스승이 핵심을 짚는 거리',
    directness: 'high',
    warmth: 'medium',
    spice: 'medium',
    teaserJob: '명식의 첫인상과 지금 가장 크게 작동하는 반복 패턴을 보여준다.',
    reportJob: '원국·오행·십성·대운·세운을 삶의 선택 기준으로 연결한다.',
    requiredScenes: ['반복되는 선택', '일과 관계의 균형', '운이 바뀌는 시기'],
    decisionCriteria: ['강하게 쓰는 기운', '보완할 기운', '지금 반복을 끊을 기준'],
    holdConditions: ['수명·질병·합격·수익 확정', '출생시간 미상 정밀 단정', '성격 낙인'],
    forbiddenCustomerCopy: ['자네 운명은 이미 정해졌네', '반드시 실패한다', '이 사주는 틀렸다'],
  },
  love_this_year: {
    serviceKey: 'love_this_year',
    serviceTitle: '올해 연애운',
    promise: '올해 관계 흐름에서 다가오는 신호와 놓치면 안 되는 경계를 같이 보여준다.',
    userQuestion: '올해 나에게 연애가 들어올까, 들어온다면 어떤 방식일까?',
    emotionalState: '기대와 불안을 동시에 가진 상태',
    conversationMode: '현실적인 연애 상담',
    relationshipDistance: '친한 상담자가 감정과 선택을 같이 정리해주는 거리',
    directness: 'medium',
    warmth: 'high',
    spice: 'medium',
    teaserJob: '올해 연애가 움직이는 핵심 타이밍과 주의할 패턴을 먼저 보여준다.',
    reportJob: '도화·세운·배우자성·관계 습관을 실제 만남 장면으로 풀어준다.',
    requiredScenes: ['새 만남', '소개·앱·모임', '연락 온도 변화'],
    decisionCriteria: ['열릴 타이밍', '헷갈리는 신호', '멈춰야 할 관계'],
    holdConditions: ['상대 마음 확정', '차단·거부 무시', '스토킹성 행동'],
    forbiddenCustomerCopy: ['그 사람이 반드시 돌아옵니다', '연락하면 무조건 잡힙니다', '외도 여부가 보입니다'],
  },
  job_choice: {
    serviceKey: 'job_choice',
    serviceTitle: '직장 선택',
    promise: '조건이 비슷한 선택지 사이에서 오래 버틸 자리와 빨리 소진될 자리를 가른다.',
    userQuestion: '이 회사/직무를 선택해도 될까?',
    emotionalState: '기회 앞에서 확신과 불안이 섞인 상태',
    conversationMode: '커리어 의사결정 코칭',
    relationshipDistance: '오퍼 조건표를 같이 보는 거리',
    directness: 'high',
    warmth: 'medium',
    spice: 'medium',
    teaserJob: '선택의 핵심 변수를 직무·돈·리듬 중 무엇인지 먼저 보여준다.',
    reportJob: '관성·식상·재성을 업무 강도, 산출 방식, 보상 구조로 번역한다.',
    requiredScenes: ['면접 후 고민', '오퍼 비교', '첫 3개월 적응'],
    decisionCriteria: ['역할 명확성', '성과 보상', '회복 가능성'],
    holdConditions: ['채용·연봉 보장', '법률 계약 해석', '회사 내부 상태 단정'],
    forbiddenCustomerCopy: ['이 회사는 반드시 합격합니다', '연봉이 오릅니다', '무조건 이직하세요'],
  },
  quit_fortune: {
    serviceKey: 'quit_fortune',
    serviceTitle: '퇴사운',
    promise: '퇴사가 탈출인지 전환인지 구분하고, 후회 줄이는 순서를 제시한다.',
    userQuestion: '지금 퇴사해도 될까, 더 버텨야 할까?',
    emotionalState: '지치고 마음은 떠났지만 손실이 두려운 상태',
    conversationMode: '냉정한 퇴사 판단 상담',
    relationshipDistance: '퇴사 메일 보내기 전 붙잡고 체크하는 거리',
    directness: 'high',
    warmth: 'medium',
    spice: 'high',
    teaserJob: '지금의 퇴사 욕구가 반복 피로인지 전환 신호인지 먼저 가른다.',
    reportJob: '직장 압박·돈·평판·다음 자리 준비도를 현실 체크리스트로 연결한다.',
    requiredScenes: ['월요일 아침', '상사와 충돌', '퇴사 통보 전날'],
    decisionCriteria: ['준비된 전환', '감정적 탈출', '버틸 조건'],
    holdConditions: ['즉시 퇴사 강요', '노동법 판단', '정신건강 위기 방치'],
    forbiddenCustomerCopy: ['오늘 당장 그만두세요', '버티면 인생이 망합니다', '회사 운이 끝났습니다'],
  },
  money_save: {
    serviceKey: 'money_save',
    serviceTitle: '돈 습관',
    promise: '돈이 새는 장면과 모이는 장면을 사주 리듬에 맞춰 생활화한다.',
    userQuestion: '왜 돈이 안 모이고, 어디부터 막아야 할까?',
    emotionalState: '열심히 버는데 잔고가 설명되지 않는 상태',
    conversationMode: '생활 밀착 돈 습관 코칭',
    relationshipDistance: '가계부를 같이 열어보는 거리',
    directness: 'high',
    warmth: 'medium',
    spice: 'medium',
    teaserJob: '이번 돈 흐름에서 새는 구멍 하나와 모이는 습관 하나를 보여준다.',
    reportJob: '재성·비겁·식상을 지출 충동, 분배, 산출 구조로 풀어낸다.',
    requiredScenes: ['월급 다음 주', '온라인 장바구니', '자동결제 정리'],
    decisionCriteria: ['막을 지출', '살릴 투자성 지출', '기록할 기준'],
    holdConditions: ['투자 수익 보장', '대출·세금 조언 확정', '가난 낙인'],
    forbiddenCustomerCopy: ['이걸 사면 돈이 들어옵니다', '투자하면 무조건 법니다', '돈복이 없어서 그렇습니다'],
  },
  cat_compatibility: {
    serviceKey: 'cat_compatibility',
    serviceTitle: '고양이 궁합',
    promise: '보호자와 고양이의 생활 리듬 차이를 귀엽지만 정확하게 풀어준다.',
    userQuestion: '우리 고양이와 나는 왜 이렇게 맞거나 엇갈릴까?',
    emotionalState: '애정은 큰데 행동을 이해하고 싶은 상태',
    conversationMode: '반려생활 번역 상담',
    relationshipDistance: '집사 옆에서 관찰 기록을 같이 보는 거리',
    directness: 'medium',
    warmth: 'high',
    spice: 'low',
    teaserJob: '우리 집에서 바로 보이는 케미 포인트와 조심할 루틴 하나를 보여준다.',
    reportJob: '보호자 기질과 고양이 루틴을 먹이·놀이·휴식 장면으로 연결한다.',
    requiredScenes: ['밥 달라는 시간', '숨는 행동', '놀이 후 예민함'],
    decisionCriteria: ['맞는 루틴', '엇갈리는 시간대', '바꿀 환경'],
    holdConditions: ['질병을 사주 탓으로 돌림', '동물행동 진단 확정', '학대·방치 정당화'],
    forbiddenCustomerCopy: ['고양이가 당신을 싫어합니다', '아픈 이유는 궁합 때문입니다', '훈육하면 고쳐집니다'],
  },
  match_couple: {
    serviceKey: 'match_couple',
    serviceTitle: '커플 궁합',
    promise: '두 사람의 잘 맞는 지점과 계속 부딪히는 지점을 현실 언어로 비교한다.',
    userQuestion: '우리 둘, 진짜 잘 맞을까?',
    emotionalState: '좋아하지만 반복되는 차이가 신경 쓰이는 상태',
    conversationMode: '관계 패턴 비교 상담',
    relationshipDistance: '둘의 대화를 옆에서 통역해주는 거리',
    directness: 'medium',
    warmth: 'high',
    spice: 'medium',
    teaserJob: '둘 사이의 강점 하나와 반복 마찰 하나를 먼저 보여준다.',
    reportJob: '합·충·일간 차이를 연락·약속·갈등 회복 방식으로 번역한다.',
    requiredScenes: ['카톡 온도', '약속 잡는 방식', '싸운 뒤 회복'],
    decisionCriteria: ['맞는 속도', '부딪히는 방식', '조율 가능한 차이'],
    holdConditions: ['결혼·이별 확정', '상대 마음 단정', '감시·질투 유발'],
    forbiddenCustomerCopy: ['둘은 반드시 헤어집니다', '상대는 당신을 속입니다', '집착해야 잡힙니다'],
  },
  marry_match: {
    serviceKey: 'marry_match',
    serviceTitle: '결혼 궁합',
    promise: '설렘보다 오래 사는 구조가 맞는지 생활 단위로 본다.',
    userQuestion: '이 사람과 결혼까지 생각해도 괜찮을까?',
    emotionalState: '큰 결정을 앞두고 현실 검증이 필요한 상태',
    conversationMode: '장기 관계 판단 상담',
    relationshipDistance: '가족·돈·생활표를 같이 펼쳐보는 거리',
    directness: 'high',
    warmth: 'medium',
    spice: 'medium',
    teaserJob: '결혼에서 가장 먼저 확인할 생활 변수 하나를 선명하게 준다.',
    reportJob: '배우자궁·대운·현실 조건을 돈·가족·집안일·거리감으로 풀어낸다.',
    requiredScenes: ['동거 상상', '양가 일정', '돈 관리 대화'],
    decisionCriteria: ['생활 합의', '갈등 복구', '장기 책임감'],
    holdConditions: ['결혼 성사 보장', '가족 문제 단정', '상대 인격 낙인'],
    forbiddenCustomerCopy: ['결혼하면 반드시 불행합니다', '이 사람은 배우자감이 아닙니다', '사주가 결혼을 금지합니다'],
  },
  couple_signal: {
    serviceKey: 'couple_signal',
    serviceTitle: '관계 신호',
    promise: '헷갈리는 연락과 태도를 내 감정과 실제 행동으로 나눠 읽는다.',
    userQuestion: '이 관계, 계속 봐도 되는 신호일까?',
    emotionalState: '상대 반응 하나에 마음이 크게 흔들리는 상태',
    conversationMode: '관계 신호 디코딩',
    relationshipDistance: '메시지 캡처를 같이 보며 감정 과열을 낮추는 거리',
    directness: 'medium',
    warmth: 'high',
    spice: 'medium',
    teaserJob: '진짜 신호와 내가 크게 해석한 신호를 먼저 분리한다.',
    reportJob: '식상·관성 흐름을 표현 방식, 책임감, 거리 조절로 번역한다.',
    requiredScenes: ['읽씹·늦답', '갑자기 다정한 말', '약속 미루기'],
    decisionCriteria: ['행동으로 확인된 신호', '내 불안의 확대', '멈출 기준'],
    holdConditions: ['차단 우회', '상대 마음 확정', '불쾌한 연락 반복'],
    forbiddenCustomerCopy: ['상대는 속으로 좋아합니다', '계속 연락하면 마음이 열립니다', '질투를 유발하세요'],
  },
  pass_angle: {
    serviceKey: 'pass_angle',
    serviceTitle: '합격각',
    promise: '합격을 점치기보다 지금 점수로 바뀔 공부 조건을 정확히 잡는다.',
    userQuestion: '이번 시험, 붙을 각이 있을까?',
    emotionalState: '남은 시간과 불안을 동시에 계산하는 상태',
    conversationMode: '시험 전략 코칭',
    relationshipDistance: '오답노트와 남은 일정을 같이 보는 거리',
    directness: 'high',
    warmth: 'medium',
    spice: 'medium',
    teaserJob: '지금 합격각을 만드는 조건과 바로 줄여야 할 공부를 보여준다.',
    reportJob: '인성·관성·식상 흐름을 암기, 규칙 적응, 답안 재현으로 연결한다.',
    requiredScenes: ['모의고사 후', '시험 전날', '시험장 입실 전'],
    decisionCriteria: ['남길 공부', '버릴 공부', '당일 컨디션 관리'],
    holdConditions: ['합격 보장', '수험 포기 강요', '건강 이상 무시'],
    forbiddenCustomerCopy: ['반드시 합격합니다', '이 공부법이 승패를 가릅니다', '운이 나빠 떨어집니다'],
  },
  work_move: {
    serviceKey: 'work_move',
    serviceTitle: '이직운',
    promise: '이직 제안과 이동 욕구를 돈·역할·생활 리듬으로 비교한다.',
    userQuestion: '지금 옮기면 좋아질까, 아니면 같은 문제가 반복될까?',
    emotionalState: '새 기회가 끌리지만 실패 비용이 걱정되는 상태',
    conversationMode: '현실형 이직 판단 상담',
    relationshipDistance: '채용공고와 현재 불만을 나란히 보는 거리',
    directness: 'high',
    warmth: 'medium',
    spice: 'medium',
    teaserJob: '이직으로 해결될 문제와 그대로 따라갈 문제를 먼저 구분한다.',
    reportJob: '대운·세운·재성·관성·식상을 새 역할의 감당력으로 번역한다.',
    requiredScenes: ['오퍼 비교', '퇴근 후 회복', '새 팀 적응'],
    decisionCriteria: ['돈 조건', '역할 권한', '생활 회복'],
    holdConditions: ['합격·연봉 확정', '기밀 회사 정보 추정', '무조건 이동 권유'],
    forbiddenCustomerCopy: ['옮기면 무조건 성공합니다', '지금 회사는 끝났습니다', '제안을 반드시 잡으세요'],
  },
  work_job: {
    serviceKey: 'work_job',
    serviceTitle: '일 적성',
    promise: '나에게 맞는 일의 방식과 피로가 쌓이는 업무 구조를 구분한다.',
    userQuestion: '나는 어떤 일을 해야 오래 잘할 수 있을까?',
    emotionalState: '직업 방향을 다시 잡고 싶은 상태',
    conversationMode: '적성·업무 방식 진단',
    relationshipDistance: '경력 연표를 같이 정리하는 거리',
    directness: 'medium',
    warmth: 'medium',
    spice: 'low',
    teaserJob: '맞는 업무 방식과 피해야 할 환경을 한 번에 잡아준다.',
    reportJob: '월주·일간·십성을 업무 속도, 협업 방식, 산출물 유형으로 연결한다.',
    requiredScenes: ['반복 업무', '기획·실행 역할', '협업 피로'],
    decisionCriteria: ['잘 버티는 업무', '빨리 소진되는 업무', '키울 역량'],
    holdConditions: ['직업 귀천 판단', '소득 보장', '성격 낙인'],
    forbiddenCustomerCopy: ['이 직업만 해야 합니다', '당신은 조직생활이 불가능합니다', '돈 못 버는 사주입니다'],
  },
  love_mind: {
    serviceKey: 'love_mind',
    serviceTitle: '그 사람 속마음',
    promise: '상대 마음을 확정하지 않고, 보이는 행동과 내 해석을 분리해 관계 온도를 읽는다.',
    userQuestion: '그 사람은 지금 나를 어떻게 생각할까?',
    emotionalState: '상대의 작은 반응을 계속 되짚는 상태',
    conversationMode: '속마음처럼 보이는 행동 신호 정리',
    relationshipDistance: '감정 과열을 낮추고 팩트를 나누는 거리',
    directness: 'medium',
    warmth: 'high',
    spice: 'medium',
    teaserJob: '상대의 진짜 마음 단정 대신 지금 확인 가능한 신호를 준다.',
    reportJob: '십성·관계 거리·최근 행동을 표현 가능성, 회피, 부담으로 나눠 읽는다.',
    requiredScenes: ['답장 텀', '갑작스러운 다정함', '약속을 피하는 말'],
    decisionCriteria: ['확인된 행동', '내 기대의 해석', '다음 질문의 방식'],
    holdConditions: ['마음 확정', '차단 우회', '몰래 확인·감시'],
    forbiddenCustomerCopy: ['속으로는 반드시 좋아합니다', '떠보면 잡힙니다', '연락을 계속 보내세요'],
  },
  love_again: {
    serviceKey: 'love_again',
    serviceTitle: '재회운',
    promise: '재회 가능성보다 다시 만나도 반복될 문제와 연락 기준을 먼저 잡는다.',
    userQuestion: '다시 연락하면 이어질 수 있을까?',
    emotionalState: '미련과 자존심, 두려움이 함께 있는 상태',
    conversationMode: '재회 판단 상담',
    relationshipDistance: '보내기 전 메시지를 멈춰 세우는 거리',
    directness: 'high',
    warmth: 'high',
    spice: 'medium',
    teaserJob: '재회 신호보다 먼저 확인해야 할 반복 문제를 보여준다.',
    reportJob: '충·합 흐름을 이별 원인, 회복 가능 조건, 멈출 기준으로 번역한다.',
    requiredScenes: ['마지막 대화', '연락 충동', '다시 만난 뒤 첫 갈등'],
    decisionCriteria: ['보내도 되는 이유', '보내면 안 되는 이유', '재회 후 조건'],
    holdConditions: ['거부 의사 무시', '차단 우회', '상대 마음 확정'],
    forbiddenCustomerCopy: ['반드시 돌아옵니다', '붙잡으면 됩니다', '질투심을 건드리세요'],
  },
  love_spouse: {
    serviceKey: 'love_spouse',
    serviceTitle: '미래 배우자',
    promise: '배우자를 예언하기보다 내가 오래 맞는 관계의 결을 구체화한다.',
    userQuestion: '나는 어떤 사람과 오래 맞을까?',
    emotionalState: '미래 관계의 그림을 알고 싶은 상태',
    conversationMode: '동반자상 해석',
    relationshipDistance: '미래 조건표를 같이 그려보는 거리',
    directness: 'medium',
    warmth: 'high',
    spice: 'low',
    teaserJob: '끌리는 사람과 오래 맞는 사람의 차이를 먼저 보여준다.',
    reportJob: '배우자궁·십성·운 흐름을 생활 태도, 대화 방식, 책임감으로 풀어낸다.',
    requiredScenes: ['처음 끌림', '일상 대화', '갈등 후 책임'],
    decisionCriteria: ['끌림', '생활 안정감', '장기 책임'],
    holdConditions: ['외모·직업·재산 확정', '혼인 시기 보장', '성별 고정 역할'],
    forbiddenCustomerCopy: ['배우자는 반드시 이런 직업입니다', '몇 살에 결혼합니다', '이 조건 아니면 안 됩니다'],
  },
  home_fit: {
    serviceKey: 'home_fit',
    serviceTitle: '집 풍수',
    promise: '지금 집과 나의 사주 리듬, 터 유사도를 겹쳐 계속 살지·무엇을 손볼지 판단하게 한다.',
    userQuestion: '지금 사는 집이 정말 나와 맞을까?',
    emotionalState: '집은 익숙하지만 피로·불편의 이유를 알고 싶은 상태',
    conversationMode: '생활 풍수 해석',
    relationshipDistance: '집 안을 같이 걸으며 한 칸씩 짚는 거리',
    directness: 'high',
    warmth: 'medium',
    spice: 'medium',
    teaserJob: '점수·터 유사도·핵심 생활 리스크를 먼저 보여주되 데이터 결손을 노출하지 않는다.',
    reportJob: '12장 구조에서 1장은 배치 요약, 나머지는 제목 주제만 깊게 다룬다.',
    requiredScenes: ['귀가 직후', '잠들기 전', '아침 피로', '책상 집중', '창밖 자극'],
    decisionCriteria: ['계속 살 각', '먼저 손볼 칸', '이사 판단을 미룰 조건'],
    holdConditions: ['부동산 매수·매도 조언', '흉지 공포', 'DEM·자료 없음 노출'],
    forbiddenCustomerCopy: ['측정 전', '자료가 아직 없어요', 'DEM 고도', '흉지입니다', '당장 이사하세요'],
  },
  newyear_flow: {
    serviceKey: 'newyear_flow',
    serviceTitle: '2027년 흐름',
    promise: '한 해를 막연한 운세가 아니라 월별 선택 리듬과 현실 사건의 대비표로 보여준다.',
    userQuestion: '내 2027년은 어느 쪽으로 풀릴까?',
    emotionalState: '새해를 앞두고 기대와 경계가 함께 있는 상태',
    conversationMode: '연간 운세 전략 브리핑',
    relationshipDistance: '1년 달력을 같이 넘겨보는 거리',
    directness: 'high',
    warmth: 'medium',
    spice: 'medium',
    teaserJob: '2027년의 큰 흐름, 조심할 달, 밀어도 되는 달을 먼저 보여준다.',
    reportJob: '세운·월운·입춘 전환을 일·돈·관계·컨디션 장면으로 풀어낸다.',
    requiredScenes: ['상반기 전환', '돈이 움직이는 달', '관계 정리', '휴식이 필요한 시기'],
    decisionCriteria: ['밀 달', '정리할 달', '돈·관계 경계선'],
    holdConditions: ['사건 발생 확정', '투자·계약 보장', '건강 위험 방치'],
    forbiddenCustomerCopy: ['2027년에 반드시 성공합니다', '이 달에는 아무것도 하지 마세요', '무조건 결혼/이직합니다'],
  },
  wedding_day: {
    serviceKey: 'wedding_day',
    serviceTitle: '결혼 택일',
    promise: '후보일을 길흉 선고가 아니라 두 사람의 준비와 충돌 조건으로 비교한다.',
    userQuestion: '우리 결혼, 이날 해도 될까?',
    emotionalState: '큰 날을 정하며 가족·예산·일정이 한꺼번에 부담되는 상태',
    conversationMode: '택일 비교 리포트',
    relationshipDistance: '후보 날짜표와 예식 준비표를 같이 보는 거리',
    directness: 'high',
    warmth: 'medium',
    spice: 'low',
    teaserJob: '가장 무난한 후보와 조심할 후보의 이유를 계산값 중심으로 보여준다.',
    reportJob: '일주·일지 합충파해·십성·절기 달을 준비 동선과 가족 일정으로 번역한다.',
    requiredScenes: ['후보일 비교', '양가 일정 조율', '예식 전날·당일 동선'],
    decisionCriteria: ['두 사람 리듬', '가족·이동 부담', '준비 여유'],
    holdConditions: ['결혼 성패 예언', '손없는날·삼재 임의 추가', '후보일 없는 확정'],
    forbiddenCustomerCopy: ['이날 결혼하면 반드시 불행합니다', '무조건 길일입니다', '손없는날이라 괜찮습니다'],
  },
}

export function serviceVoiceContract(serviceKey: KnownServiceKey): ServiceVoiceContract {
  return SERVICE_VOICE_CONTRACTS[serviceKey]
}

export function formatServiceVoiceContract(serviceKey: KnownServiceKey): string {
  const contract = serviceVoiceContract(serviceKey)
  return [
    `### 서비스별 해석 계약 · ${contract.serviceTitle}`,
    `- 서비스 약속: ${contract.promise}`,
    `- 사용자의 속질문: ${contract.userQuestion}`,
    `- 감정 상태: ${contract.emotionalState}`,
    `- 대화 방식: ${contract.conversationMode}`,
    `- 거리감: ${contract.relationshipDistance}`,
    `- 온도값: 직설 ${contract.directness}, 온기 ${contract.warmth}, 맛 ${contract.spice}`,
    `- 티저 임무: ${contract.teaserJob}`,
    `- 전체 해석 임무: ${contract.reportJob}`,
    `- 반드시 생활 장면으로 번역: ${contract.requiredScenes.join(' · ')}`,
    `- 판단 기준: ${contract.decisionCriteria.join(' · ')}`,
    `- 멈춤 조건: ${contract.holdConditions.join(' · ')}`,
    `- 고객 본문 금지문: ${contract.forbiddenCustomerCopy.join(' · ')}`,
  ].join('\n')
}
