window.reportPreviewServices = [
  {
    key: 'cmdg', title: '천명사주', category: '종합', source: 'verified', image: 'assets/services/cmdg.webp',
    question: '내 기준을 언제, 어떻게 말하는지가 중요해요.',
    conclusion: '새로운 책임을 더하기 전에, 이미 맡은 일의 범위와 순서를 정리해 보세요.',
    summary: '보관함 해석은 자기 기준을 세우는 힘과, 그 기준을 말하지 않은 채 혼자 책임을 떠안는 반복을 함께 짚습니다. 일과 관계에서 맡을 몫과 맡지 않을 몫을 먼저 밝히라는 내용입니다.',
    sections: ['타고난 기질', '일과 돈의 선택', '관계에서 반복되는 기준'],
    teaser: {
      longform: true,
      title: '지금의 고민을 타고난 성향과 함께 살펴봅니다',
      lead: '일의 우선순위가 고민이라면, 빠른 판단이 장점이 되는 때와 부담이 되는 때를 나누어 봅니다.',
      signals: [
        ['먼저 보이는 성향', '상황을 빨리 읽고 판단하는 편인지 살펴봅니다.'],
        ['지금의 질문', '맡은 일을 어떤 순서로 정리할지 확인합니다.'],
        ['더 볼 내용', '일·돈·관계에서 같은 선택이 반복되는지 살펴봅니다.'],
      ],
      sections: [
        ['먼저 보이는 결', '빠르게 판단하고 반응하는 성향이 강하게 보입니다. 장점은 살리고, 혼자 너무 많이 떠안는 순간은 나누어 봅니다.'],
        ['숨은 흐름', '지금의 선택이 멈춘 것이 아니라 쌓이는 중인지, 무리할 때 무엇이 새는지 확인합니다.'],
        ['돈과 현실', '돈이 모이는 자리와 새는 자리를 나누어 보고, 실제 수입·지출과 추상적인 해석을 구분합니다.'],
        ['관계와 선택', '끌리는 사람보다 오래 남는 관계의 조건, 지금 버틸지 움직일지 판단할 현실 기준을 정리합니다.'],
        ['상세 리포트 예고', '성향·일·돈·관계의 흐름을 하나의 질문에 맞춰 더 깊게 연결합니다.'],
      ],
    },
  },
  {
    key: 'love_this_year', title: '올해 연애운', category: '연애', source: 'verified', image: 'assets/services/love_this_year.webp',
    question: '올해는 기다리기보다 만날 자리를 만들 때예요.',
    conclusion: '새 만남을 기다리기만 하지 말고, 사람을 직접 만나는 자리를 넓혀 보세요.',
    summary: '보관함 해석은 연락의 분위기보다 실제 약속이 잡히는지를 기준으로 삼습니다. 거절이나 차단이 있다면 더 밀지 않는다는 경계도 함께 제시합니다.',
    sections: ['새 만남이 열리는 자리', '놓치기 쉬운 신호', '올해 해 볼 작은 행동'],
    teaser: {
      title: '올해는 만남의 자리를 넓히되, 실제 약속을 봅니다',
      lead: '소개·앱·모임에서 마음이 끌려도, 만날 날짜를 함께 정하는지 확인해 보세요.',
      signals: [
        ['올해의 방향', '새 사람을 만날 기회를 스스로 만들어 봅니다.'],
        ['확인할 행동', '말보다 구체적인 약속과 꾸준한 행동을 살펴봅니다.'],
        ['지킬 경계', '거절이나 차단을 받았다면 더 연락하지 않습니다.'],
      ],
    },
  },
  {
    key: 'job_choice', title: '직장 선택', category: '직업', source: 'verified', image: 'assets/services/job_choice.webp',
    question: '좋아 보이는 조건보다 오래 다닐 수 있는지 보세요.',
    conclusion: '출퇴근과 업무 부담을 감당할 수 있는지 확인하기 전에는 결정을 미뤄 보세요.',
    summary: '보관함 해석은 특정 회사명과 직책을 다루지만, 작업실에는 이를 제거했습니다. 역할 범위와 지원 인력, 이동 시간을 함께 비교하는 판단 구조만 남겼습니다.',
    sections: ['제안 조건 비교', '지속 가능한 일상', '결정 전 확인 질문'],
    teaser: {
      title: '이 제안은 근무 조건부터 확인해 보세요',
      lead: '일 자체보다 출퇴근과 근무 방식이 오래 다닐 수 있는지를 가를 수 있습니다.',
      signals: [
        ['먼저 보이는 신호', '업무 환경과 이동 부담이 핵심입니다.'],
        ['확인할 조건', '실제 출근 요일, 이동 빈도, 야근 기준을 물어봅니다.'],
        ['방해 요인', '처음엔 괜찮아도 이동 피로가 쌓이면 판단이 달라질 수 있습니다.'],
      ],
    },
  },
  {
    key: 'cat_compatibility', title: '고양이 궁합', category: '궁합', source: 'verified', image: 'assets/services/cat_compatibility.webp',
    question: '우리 고양이에게 먼저 필요한 건 숨을 자리예요.',
    conclusion: '손길을 늘리기 전에 편히 숨고 움직일 수 있는 공간부터 살펴보세요.',
    summary: '보관함 해석은 낯가림과 예민함을 보이는 반려묘를 예로 들어, 사람의 애정 표현보다 고양이의 이동 동선과 안전한 자리를 먼저 보라고 안내합니다.',
    sections: ['함께 사는 박자', '공간에서 보이는 신호', '이번 주 바꿀 한 가지'],
    teaser: {
      title: '함께 편해지는 시작은 거리와 생활 습관입니다',
      lead: '고양이가 스스로 쉴 수 있는 자리와 움직이는 길을 먼저 살펴보세요.',
      signals: [
        ['첫 신호', '편하게 머물 수 있는 공간이 있는지 확인합니다.'],
        ['생활 조건', '화장실 위치와 이동 길이 막히지 않았는지 봅니다.'],
        ['살펴볼 점', '보호자의 기대보다 고양이가 실제로 보인 행동을 기준으로 삼습니다.'],
      ],
    },
  },
  {
    key: 'lucky_color', title: '나한테 운 붙는 색과 물건', category: '흐름', source: 'template', image: 'assets/services/lucky_color.webp',
    question: '색과 물건을 생활에서 어떻게 써 볼까요?',
    conclusion: '추천 색과 소재의 이유를 쉬운 말로 보여 줄 자리입니다.',
    summary: 'good1621 보관함에서 이 서비스의 해석 본문을 확인하지 못했습니다. 아래 목차는 공개 서비스 설명을 바탕으로 한 디자인 틀입니다.',
    sections: ['채울 색', '덜어낼 색', '생활에서 써 보는 방법'],
  },
  {
    key: 'newyear_flow', title: '내 2027년, 풀릴 각이야?', category: '흐름', source: 'template', image: 'assets/services/newyear_flow.webp',
    question: '한 해의 흐름을 월별로 읽는 자리입니다.',
    conclusion: '월별 해석과 현실 행동을 나란히 보여 줄 자리입니다.',
    summary: 'good1621 보관함의 실제 본문은 확인하지 못했습니다. 연간·월간 흐름이라는 서비스 구조만 표시합니다.',
    sections: ['올해의 큰 흐름', '달마다 달라지는 점', '미리 준비할 일'],
  },
  {
    key: 'wedding_day', title: '우리 결혼, 이날 해도 될까?', category: '택일', source: 'template', image: 'assets/services/wedding_day.webp',
    question: '날짜보다 두 사람의 현실 조건을 먼저 봅니다.',
    conclusion: '후보 날짜마다 실제 일정과 조건을 비교할 자리입니다.',
    summary: 'good1621 보관함의 실제 본문은 확인하지 못했습니다. 날짜 비교 화면을 디자인하기 위한 서비스 설명 기반 틀입니다.',
    sections: ['후보 날짜 비교', '두 사람의 일정', '결정 전 확인할 조건'],
  },
  {
    key: 'match_couple', title: '커플궁합', category: '궁합', source: 'verified', image: 'assets/services/match_couple.webp',
    question: '안 맞는 사이라기보다 말투가 먼저 부딪힐 수 있어요.',
    conclusion: '싸운 뒤 어떤 말로 다시 대화를 시작할지 함께 정해 보세요.',
    summary: '보관함 해석은 관계의 결과를 단정하지 않고, 말투와 거리감이 어긋나는 장면을 살핀 뒤 회복할 때 쓸 문장을 합의하라고 제안합니다.',
    sections: ['둘 사이의 끌림', '갈등이 생기는 말투', '다시 대화하는 방법'],
    teaser: {
      syntheticPartner: true,
      title: '좋아하는 마음과 대화 방식은 따로 살펴보세요',
      lead: '가상 상대를 넣어 확인한 무료 화면입니다. 실제 두 사람에 대한 판단은 아닙니다.',
      signals: [
        ['강한 신호', '호감만 보지 말고 연락과 말투가 반복되는 방식을 봅니다.'],
        ['확인 조건', '두 사람의 정보가 서로 섞이지 않았는지 확인합니다.'],
        ['방해 요인', '서운함이 커질 때는 추측보다 확인할 질문을 먼저 정합니다.'],
        ['오늘 할 일', '느낀 감정과 실제 확인하고 싶은 사실을 한 문장씩 나눕니다.'],
      ],
    },
  },
  {
    key: 'marry_match', title: '결혼궁합', category: '궁합', source: 'verified', image: 'assets/services/marry_match.webp',
    question: '결혼 날짜보다 먼저 맞출 약속이 있어요.',
    conclusion: '돈·생활 거리·가족 일정을 먼저 합의한 뒤 날짜를 정해 보세요.',
    summary: '보관함 해석은 결혼 가능성을 확정하지 않고, 돈 관리 방식을 맨 앞에 두고 말투·생활·가족 일정을 함께 조율하는 순서를 제시합니다.',
    sections: ['생활 기준 맞추기', '돈 관리 합의', '날짜를 정하기 전 점검'],
    teaser: {
      syntheticPartner: true,
      title: '결혼 여부보다 생활 기준을 먼저 맞춰 보세요',
      lead: '가상 상대를 넣어 무료 화면의 구성을 확인했습니다. 실제 결혼 가능성을 뜻하지 않습니다.',
      signals: [
        ['강한 신호', '서로 다른 생활 속도와 표현 방식을 따로 살펴봅니다.'],
        ['시기 조건', '약속과 경계를 어떻게 맞추는지가 먼저입니다.'],
        ['방해 요인', '돈·가족·생활 습관 이야기를 미루면 피로가 커질 수 있습니다.'],
      ],
    },
  },
  {
    key: 'couple_signal', title: '내 애인 바람필까?', category: '연애', source: 'verified', image: 'assets/services/couple_signal.png',
    question: '연락의 온도만으로 상대 마음을 단정하지 마세요.',
    conclusion: '말투보다 약속을 실제로 잡는 행동을 살펴보세요.',
    summary: '보관함 해석은 답장 속도, 다정한 표현, 실제 만남을 구분합니다. 불쾌한 연락이나 거절이 반복되면 마음 해석보다 거리를 두는 일을 우선합니다.',
    sections: ['지금 관계의 온도', '오해하기 쉬운 신호', '다음 연락에서 볼 행동'],
    teaser: {
      syntheticPartner: true,
      title: '답장 속도만으로 마음을 단정하지 마세요',
      lead: '가상 상대를 넣어 확인한 무료 화면입니다. 외도 여부나 실제 상대의 마음을 판정하지 않습니다.',
      signals: [
        ['강한 신호', '말투와 약속을 잡는 행동이 함께 달라졌는지 봅니다.'],
        ['확인 조건', '답장 간격·약속 변경·표현 감소가 같은 때 반복되는지 확인합니다.'],
        ['방해 요인', '불안할수록 추궁보다 사실을 묻는 질문이 필요합니다.'],
      ],
    },
  },
  {
    key: 'quit_fortune', title: '퇴사운', category: '직업', source: 'verified', image: 'assets/services/quit_fortune.png',
    question: '퇴사가 떠올라도 통보는 준비 뒤에 하세요.',
    conclusion: '퇴사를 검토하되, 재직 중 다음 자리를 준비하는 순서부터 세워 보세요.',
    summary: '보관함 해석은 지금의 답답함을 인정하면서도, 즉시 퇴사 통보를 하기보다 전환 준비와 생활 조건을 점검하라고 안내합니다.',
    sections: ['지금 나가고 싶은 이유', '남아 있는 동안 준비할 일', '결정 전에 확인할 조건'],
    teaser: {
      title: '떠날 이유와 남을 이유를 함께 놓고 판단합니다',
      lead: '퇴사 의지가 분명해도 다음 자리와 생활 계획이 불확실하다면, 날짜부터 정하지 않는 편이 좋습니다.',
      signals: [
        ['현재 판단', '지금 힘든 이유를 일 자체와 일하는 조건으로 나누어 봅니다.'],
        ['먼저 할 일', '재직 중 다음 자리와 생활비 계획을 준비합니다.'],
        ['결정 조건', '준비가 확인된 뒤 퇴사 시기를 다시 정합니다.'],
      ],
    },
  },
  {
    key: 'pass_angle', title: '나, 붙을 각이야?', category: '직업', source: 'template', image: 'assets/services/pass_angle.png',
    question: '시험 흐름을 공부 계획과 함께 봅니다.',
    conclusion: '공부 방법과 시험 준비 상황을 비교할 자리입니다.',
    summary: 'good1621 보관함의 실제 본문은 확인하지 못했습니다. 공개 서비스 설명을 바탕으로 한 디자인 틀입니다.',
    sections: ['준비 상태', '공부 방법', '시험 전 점검'],
  },
  {
    key: 'money_save', title: '소비성향', category: '재물', source: 'verified', image: 'assets/services/money_save.png',
    question: '돈복보다 먼저 새는 지출을 살펴보세요.',
    conclusion: '반복되는 배달·구독 지출부터 확인하고, 필요한 모임 비용은 기준을 세워 남겨 보세요.',
    summary: '보관함 해석은 모든 지출을 끊으라고 하지 않습니다. 월급 뒤에 먼저 빠져나가는 반복 비용과 삶에 필요한 모임 비용을 구분합니다.',
    sections: ['돈이 빠져나가는 자리', '남겨도 되는 지출', '이번 달 실천'],
    teaser: {
      title: '돈이 들어오는데도 남지 않는 장면부터 봅니다',
      lead: '무료 티저는 지금 돈이 새는 방향과 첫 행동을 먼저 보여 줍니다.',
      signals: [
        ['입력한 상황', '반복되는 생활비와 구독료를 따로 적어 봅니다.'],
        ['강한 신호', '같이 쓰는 돈과 정산 기준이 흐려질 때를 확인합니다.'],
        ['첫 행동', '예정된 저축·고정비와 계획 밖 지출을 구분합니다.'],
      ],
    },
  },
  {
    key: 'work_move', title: '이직운', category: '직업', source: 'verified', image: 'assets/services/work_move.webp',
    question: '연봉보다 내 일이 어디까지인지 먼저 보세요.',
    conclusion: '새 자리의 업무 범위·권한·평가 기준이 문서에 적혔을 때 이직을 검토해 보세요.',
    summary: '보관함 해석은 연봉이 오르는 제안이라도 맡을 일이 끝없이 넓으면 판단을 미루라고 합니다. 현재 직장과 새 제안의 역할 문서를 나란히 비교하는 것이 핵심입니다.',
    sections: ['옮길 자리와 남을 자리', '현 회사에서 걸리는 신호', '결정 전 문서 확인'],
    teaser: {
      title: '조건 확인 전엔 환승 선언 금지입니다',
      lead: '연봉과 업무 범위가 선명해진 뒤 이직을 판단하는 쪽에 가깝습니다.',
      signals: [
        ['한 줄 방향', '돈 조건 확인 전엔 서두르지 마세요.'],
        ['강한 신호', '역할 범위가 핵심입니다.'],
        ['조건 또는 시기', '급여와 평가 기준은 아직 확인이 필요합니다.'],
        ['방해 요인', '역할과 책임이 흐리면 새 회사에서도 같은 피로가 반복될 수 있습니다.'],
      ],
    },
  },
  {
    key: 'work_job', title: '직업운', category: '직업', source: 'template', image: 'assets/services/work_job.png',
    question: '나와 맞는 일의 방식을 살펴봅니다.',
    conclusion: '일하는 환경과 역할을 비교할 자리입니다.',
    summary: 'good1621 보관함의 실제 본문은 확인하지 못했습니다. 공개 서비스 설명을 바탕으로 한 디자인 틀입니다.',
    sections: ['일하는 방식', '맞는 환경', '다음 선택의 기준'],
  },
  {
    key: 'love_mind', title: '상대방 마음', category: '연애', source: 'template', image: 'assets/reading-list-cover.webp',
    question: '상대의 속마음 대신 확인할 행동을 봅니다.',
    conclusion: '상대가 직접 보여 준 말과 행동을 나누어 볼 자리입니다.',
    summary: 'good1621 보관함의 실제 본문은 확인하지 못했습니다. 속마음을 확정하지 않는 편집용 구조입니다.',
    sections: ['확인된 행동', '내가 궁금한 점', '대화로 확인할 방법'],
  },
  {
    key: 'love_again', title: '재회운', category: '연애', source: 'template', image: 'assets/reading-list-cover.webp',
    question: '다시 연락하기 전에 서로의 경계를 봅니다.',
    conclusion: '상대가 거절했다면 재회 해석보다 멈추는 일이 먼저입니다.',
    summary: 'good1621 보관함의 실제 본문은 확인하지 못했습니다. 공개 서비스 설명과 관계 안전 원칙만 적용한 틀입니다.',
    sections: ['현재 연락 상태', '서로의 경계', '내가 할 수 있는 선택'],
  },
  {
    key: 'love_spouse', title: '배우자운', category: '연애', source: 'template', image: 'assets/reading-list-cover.webp',
    question: '미래의 한 사람보다 내 관계 기준을 봅니다.',
    conclusion: '함께 살 때 중요한 기준을 스스로 정리할 자리입니다.',
    summary: 'good1621 보관함의 실제 본문은 확인하지 못했습니다. 미래 배우자의 신원이나 만남 시기를 단정하지 않는 틀입니다.',
    sections: ['내 관계 기준', '함께 살 때 중요한 점', '만남에서 볼 행동'],
  },
  {
    key: 'home_pungsu', title: '집 풍수', category: '풍수', source: 'template', image: 'assets/services/home_pungsu.webp',
    question: '집에서 바꿀 수 있는 생활 조건부터 봅니다.',
    conclusion: '공간의 불편함을 실제 생활 동선과 함께 살펴볼 자리입니다.',
    summary: 'good1621 보관함의 실제 본문은 확인하지 못했습니다. 주소나 위치 정보 없이 공개 서비스 설명만으로 만든 틀입니다.',
    sections: ['공간의 현재 상태', '생활 동선', '바꿔 볼 한 가지'],
  },
  {
    key: 'today_fortune', title: '오늘운', category: '무료', source: 'verified', image: 'assets/teaser-hero.webp',
    question: '기대를 키우기 전에 조건을 분명히 정하세요.',
    conclusion: '새로운 기회와 그에 드는 시간·비용을 함께 적어 보고, 필요한 정보 하나를 행동으로 옮겨 보세요.',
    summary: '보관함의 저장 오늘운은 일·돈·관계·주의할 점을 점수와 함께 나누어 보여 줍니다. 일은 마무리 기준, 돈은 확정된 금액, 관계는 물어보고 합의한 범위를 확인하라고 안내합니다.',
    sections: ['오늘의 흐름', '일·돈·관계', '오늘 기억할 한 가지'],
  },
]
