import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { getCorpusSnapshot } from '../../src/rag/corpus-registry.js'
import { retrieveRagChunks } from '../../src/rag/retriever.js'
import { buildTemplateSajuReport, reviewGeneratedSajuReportSection, sectionPrompt } from '../../src/report/report-generator.js'
import { analyzeSaju } from '../../src/saju/analyzer.js'
import type { BirthInput, CorpusSnapshot, SajuReportContext } from '../../src/types/index.js'

const root = process.cwd()
const oldPath = 'tone-v2/corpus/cat-compatibility-service.json'
const newPath = 'tone-v2/corpus/releases/cat-compatibility-service-2.1.0.json'
const oldMarker = '돌봄은 많이 하는 쪽이 아니라 상대가 받을 수 있는 속도로 하는 쪽이 남는다'
const newMarker = '보호자의 사주 계산은 고양이의 성격이나 마음을 증명하지 않는다'
const birth: BirthInput = { year: 1985, month: 3, day: 20, hour: 9, gender: 'male', calendar: 'solar' }
const context: SajuReportContext = { serviceKey: 'cat_compatibility', concern: '1묘 가정 · 손길은 짧게 허용 · 밤 활동과 식사 변화를 관찰했어요.' }
const hashFile = (path: string) => createHash('sha256').update(readFileSync(join(root, 'data', path), 'utf8')).digest('hex')
function oldSnapshot(): CorpusSnapshot { const current = getCorpusSnapshot(); return { ...current, registryVersion: 'tone-v2.2.0.13', fingerprint: 'old-cat-compatibility', activePacks: current.activePacks.map((pack) => pack.id === 'cat-compatibility-service' ? { ...pack, path: oldPath, version: '2.0.0', contentHash: hashFile(oldPath).slice(0, 16) } : pack) } }

describe('[TASK P05] cat_compatibility corpus/RAG release candidate', () => {
  it('activates reviewed 2.1.0 and retains 2.0.0', () => { const pack = getCorpusSnapshot().activePacks.find((item) => item.id === 'cat-compatibility-service'); assert.equal(pack?.version, '2.1.0'); assert.equal(pack?.path, newPath); assert.doesNotThrow(() => readFileSync(join(root, 'data', oldPath))); assert.equal(pack?.contentHash, hashFile(newPath).slice(0, 16)) })
  it('records thirty-eight semantic-review passes', () => { const review = JSON.parse(readFileSync(join(root, 'tone-v2/corpus-review/cat-compatibility-2.1.0.json'), 'utf8')); assert.equal(review.status, 'approved'); assert.equal(review.sourcePath, `data/${newPath}`); assert.equal(review.sourceSha256, hashFile(newPath)); assert.equal(review.sampleOutputsIngested, false); assert.equal(review.blocks.length, 38); assert.deepEqual(review.blocks.map((item: any) => item.id), Array.from({ length: 38 }, (_, index) => `cat-${String(index + 1).padStart(3, '0')}`)); assert.ok(review.blocks.every((block: any) => block.status === 'pass' && Object.values(block.checks).every(Boolean))) })
  it('enforces observation, animal-welfare, symbolic and numeric boundaries', () => { const pack = JSON.parse(readFileSync(join(root, 'data', newPath), 'utf8')); const blocks = pack.knowledgeBlocks; const text = blocks.map((block: any) => [block.concept, block.condition, block.interpretation, ...block.real_world_pattern, block.risk, block.opportunity, block.advice, block.forbidden_generalization].join(' ')).join(' '); const guidance = blocks.map((block: any) => [block.concept, block.interpretation, ...block.real_world_pattern, block.opportunity, block.advice].join(' ')).join(' '); assert.equal(blocks.length, 38); assert.equal(new Set(blocks.map((block: any) => block.interpretation)).size, 38); assert.equal(new Set(blocks.flatMap((block: any) => block.real_world_pattern)).size, 76); assert.ok(blocks.every((block: any) => block.real_world_pattern.every((item: string) => item.startsWith('가상 사례:')))); assert.ok(blocks.every((block: any) => /사용자가 입력하거나 관찰한/.test(block.condition) && /보호자 사주 계산/.test(block.condition) && /알 수 없음/.test(block.condition))); assert.doesNotMatch(text, /현재 항목과 계산값이 직접 연결될 때만 사용한다/); assert.match(text, new RegExp(newMarker)); assert.match(text, /수의사/); assert.match(text, /1묘|다묘/); assert.doesNotMatch(guidance, /사흘|이틀|일주일|2주|세 번|하루 한 번|한두 번|반드시 잡게|성패가 갈린다|관계는 앞으로 간다/); assert.doesNotMatch(guidance, /분리불안이 생긴다|고양이는 .*기억한다|고양이는 .*느낀다|다음 접근은 고양이 쪽에서 온다/) })
  it('separates active and stored retrieval', () => { const analysis = analyzeSaju(birth); const active = retrieveRagChunks('고양이 집사 관찰 돌봄 거리 루틴', analysis, 30, context); const old = retrieveRagChunks('고양이 집사 관찰 돌봄 거리 루틴', analysis, 30, context, oldSnapshot()); const activeText = active.map((item) => item.content).join('\n'); const oldText = old.map((item) => item.content).join('\n'); assert.ok(active.some((item) => item.domain === 'cat_compatibility_service')); assert.ok(old.some((item) => item.domain === 'cat_compatibility_service')); assert.match(activeText, new RegExp(newMarker)); assert.doesNotMatch(activeText, new RegExp(oldMarker)); assert.match(oldText, new RegExp(oldMarker)); assert.doesNotMatch(oldText, new RegExp(newMarker)) })
  it('fails closed on stored hash mismatch', () => { const snapshot = oldSnapshot(); snapshot.activePacks = snapshot.activePacks.map((pack) => pack.id === 'cat-compatibility-service' ? { ...pack, contentHash: '0000000000000000' } : pack); assert.throws(() => retrieveRagChunks('고양이 돌봄', analyzeSaju(birth), 30, context, snapshot), /Corpus snapshot hash mismatch: cat-compatibility-service/) })
  it('builds prompts from stored snapshot', () => { const analysis = analyzeSaju(birth); const section = buildTemplateSajuReport(analysis, birth, context).sections[0]; assert.ok(section); const active = sectionPrompt(analysis, birth, context, section).map((item) => item.content).join('\n'); const old = sectionPrompt(analysis, birth, context, section, [], oldSnapshot()).map((item) => item.content).join('\n'); assert.match(active, new RegExp(newMarker)); assert.doesNotMatch(active, new RegExp(oldMarker)); assert.match(old, new RegExp(oldMarker)); assert.doesNotMatch(old, new RegExp(newMarker)) })
  it('reviews saved prose against stored snapshot', () => { const analysis = analyzeSaju(birth); const section = buildTemplateSajuReport(analysis, birth, context).sections[0]; assert.ok(section); const common = { analysis, birth, context, section, hook: '입력된 관찰과 모르는 상태를 구분해요.', interpretation: `${oldMarker}.` }; const issue = '코퍼스 문장을 복사하지 말고 현재 질문과 근거에 맞는 새 문장으로 다시 쓰세요.'; assert.ok(!reviewGeneratedSajuReportSection(common).issues.includes(issue)); assert.ok(reviewGeneratedSajuReportSection({ ...common, corpusSnapshot: oldSnapshot() }).issues.includes(issue)) })
  it('binds a truthful reversible local candidate', () => { const manifest = JSON.parse(readFileSync(join(root, 'tone-v2/releases/cat-compatibility-2.1.0.json'), 'utf8')); assert.equal(manifest.state, 'candidate'); assert.equal(manifest.deployed, false); assert.equal(manifest.serviceKey, 'cat_compatibility'); assert.equal(manifest.generationEvidence, null); assert.match(manifest.generationEvidenceReason, /no provider evaluation/i); assert.deepEqual(manifest.corpus.candidate, { path: `data/${newPath}`, version: '2.1.0', sha256: hashFile(newPath) }); assert.deepEqual(manifest.corpus.previous, { path: `data/${oldPath}`, version: '2.0.0', sha256: hashFile(oldPath) }); assert.equal(manifest.attachment.newReportsOnly, true); assert.equal(manifest.attachment.customerRecordMutation, false); assert.equal(manifest.rollback.strategy, 'registry_only'); assert.equal(manifest.verificationEvidence, 'tone-v2/evaluations/P05-cat-compatibility-corpus-rag-release-candidate-20260913.json'); assert.ok(Object.values(manifest.gates).every((value) => value !== 'pending')) })
})
