import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { test } from 'node:test'

const review = readFileSync(new URL('../../design-workspace/actual-service-pages/review/cmdg-longform.html', import.meta.url), 'utf8')
const styles = readFileSync(new URL('../../design-workspace/actual-service-pages/review/cmdg-longform.css', import.meta.url), 'utf8')
const editorial = readFileSync(new URL('../../design-workspace/actual-service-pages/review/cmdg-longform-review.js', import.meta.url), 'utf8')
const highlightAsset = new URL('../../design-workspace/actual-service-pages/site/사주/assets/cmdg-wood-order-highlight-v1.png', import.meta.url)
const detailImageDirectory = new URL('../../design-workspace/actual-service-pages/site/사주/assets/cmdg-review/', import.meta.url)

test('cmdg longform review is isolated from the production page and uses the review-only highlight asset', () => {
  assert.match(review, /격리 검토본 · 운영 반영 전/)
  assert.match(review, /cmdg-wood-order-highlight-v1\.png/)
  assert.match(review, /umsh-cmdg-card-bg\.webp/)
  assert.match(review, /운명상회 공통 상단/)
  assert.match(review, /운명상회 공통 하단/)
  assert.equal((review.match(/<details class="reading-card"/g) || []).length, 16, '운영 저장 해석의 16개 해석 카드를 보여야 한다')
  assert.equal((review.match(/class="umsh-highlight"/g) || []).length, 3, '운영 하이라이트 세 장을 보여야 한다')
  assert.ok(existsSync(highlightAsset), '검토용 하이라이트 이미지가 없다')
})

test('cmdg review assigns a distinct photoreal image to every saved interpretation card', () => {
  const detailImages = [...review.matchAll(/cmdg-review\/(\d{2}-[\w-]+\.png)/g)].map((match) => match[1])

  assert.equal(detailImages.length, 16, '16개 해석 카드 모두에 검토용 이미지를 붙여야 한다')
  assert.equal(new Set(detailImages).size, 16, '서로 다른 해석 카드에 같은 이미지를 재사용하지 않는다')
  assert.doesNotMatch(review, /hero-mystic\.webp/, '공통 일러스트를 해석 카드에 사용하지 않는다')

  for (const image of detailImages) {
    assert.ok(existsSync(new URL(image, detailImageDirectory)), `${image} 파일이 없다`)
  }
})

test('cmdg review keeps every saved interpretation as a complete answer, evidence, and action set', () => {
  assert.equal((review.match(/class="reading-block reading-answer"/g) || []).length, 16)
  assert.equal((review.match(/class="reading-block reading-evidence"/g) || []).length, 16)
  assert.equal((review.match(/class="reading-block reading-action"/g) || []).length, 16)
  assert.match(review, /운이 바뀌는 시기를 기다리기보다, 같은 자리에서 기준을 바꾸는 반복부터 줄이는 것이 다음 선택의 출발점입니다\./)
  assert.match(review, /하나라도 비어 있으면 수락보다 다시 상의하는 것이 다음 판단 기준입니다\./)
})

test('cmdg review displays the full summary source instead of banner-cropping it', () => {
  assert.match(styles, /\.umsh-summary-figure\s*\{[^}]*aspect-ratio:\s*auto;[^}]*max-height:\s*none;/s)
  assert.match(styles, /\.umsh-summary-figure img\s*\{[^}]*width:\s*100%;[^}]*height:\s*auto;[^}]*object-fit:\s*contain;/s)
  assert.match(styles, /\.umsh-summary-figure::after\s*\{\s*display:\s*none;\s*\}/)
})

test('cmdg editorial review preserves full original interpretation while adding sixteen plain-language titles and visual guides', () => {
  assert.match(review, /cmdg-longform-review\.js/)
  assert.match(review, /cmdg-longform-review\.js\?v=20260922-domain-flow-v8/)
  assert.match(review, /cmdg-longform\.css\?v=20260922-toggle-state-v5/)
  assert.equal((editorial.match(/^      title:/gm) || []).length, 16)
  assert.match(editorial, /const visual = renderVisual\(copy\.visual\)/)
  assert.match(editorial, /originalAnswer\.after\(visual\)/)
  assert.match(editorial, /originalEvidence\.after\(evidence\)/)
  assert.match(editorial, /originalAction\.after\(action\)/)
  assert.doesNotMatch(editorial, /source\.append\(block\)/, '원문을 접힌 영역으로 옮기면 안 된다')
  assert.match(editorial, /'다음 만남을 정할 때 살필 점'/)
  assert.match(editorial, /'지금 일, 계속할까 옮길까'/)
  assert.match(editorial, /visual: \{ type: 'table'/)
  assert.match(editorial, /visual: \{ type: 'facts'/)
})

test('cmdg review has no PDF download control in the design review scope', () => {
  assert.doesNotMatch(review, /data-review-pdf|PDF 다운받기/)
  assert.doesNotMatch(editorial, /beforeprint|afterprint|window\.print/)
  assert.doesNotMatch(styles, /review-pdf-dock/)
})

test('cmdg review lets a reader add only needed real-world context without persisting it', () => {
  assert.match(editorial, /additionalContextDefinitions/)
  assert.match(editorial, /workDecision/)
  assert.match(editorial, /\['current', '현재 자리의 조건'/)
  assert.match(editorial, /\['new', '새 선택의 조건'/)
  assert.match(editorial, /\['condition', '제안의 실제 조건'/)
  assert.match(editorial, /\['condition', '관계의 실제 조건'/)
  assert.match(editorial, /\['condition', '현재 계획의 실제 조건'/)
  assert.doesNotMatch(editorial, /currentRole|currentEvaluation|currentEnergy|currentReward|newRole|newEvaluation|newEnergy/)
  assert.match(editorial, /추가 정보 입력/)
  assert.match(editorial, /저장하거나 전송하지 않습니다/)
  assert.match(editorial, /data-context-value/)
  assert.match(editorial, /textContent = contextValueOrPlaceholder/)
  assert.match(editorial, /const renderedContexts = new Set\(\)/)
  assert.match(editorial, /copy\.context && !renderedContexts\.has\(copy\.context\)/)
  assert.doesNotMatch(editorial, /localStorage|sessionStorage|fetch\s*\(/)
})

test('cmdg review shows an evidence-first life flow map instead of an invented fortune score', () => {
  assert.match(editorial, /lifeFlowProfile/)
  assert.match(editorial, /경진 대운 안의 2026년 병오 참고점/)
  assert.match(editorial, /daewoon: \[/)
  assert.match(editorial, /갑신|甲申/)
  assert.match(editorial, /을해|乙亥/)
  assert.match(editorial, /review-daewoon-graph/)
  assert.match(editorial, /review-daewoon-segment is-current/)
  assert.match(editorial, /review-life-curve/)
  assert.match(editorial, /힘을 쓰기 쉬운 흐름/)
  assert.match(editorial, /속도를 조절할 흐름/)
  assert.match(editorial, /만세력 원자료 보기/)
  assert.match(editorial, /source\.open = true/)
  assert.match(editorial, /calculateSamjae/)
  assert.match(editorial, /birthYearBranch: '卯'/)
  assert.match(editorial, /referenceYear: 2026/)
  assert.match(editorial, /\['들어가는 해', '가운데 해', '마무리 해'\]/)
  assert.match(editorial, /삼재는 전통적인 해 분류일 뿐/)
  assert.doesNotMatch(editorial, /계산값 미연결/)
  assert.doesNotMatch(editorial, /삼재 계산 결과가 없어/)
  assert.match(editorial, /리포트에 연결된 정보/)
  assert.match(editorial, /사주 구성·대운·2026년 참고·삼재/)
  assert.match(editorial, /제안 1 · 일·직장 2 · 관계 1 · 계획 1/)
  assert.match(editorial, /재물·보상/)
  assert.match(editorial, /일·직장/)
  assert.match(editorial, /관계·연애/)
  assert.match(editorial, /domainFlowProfiles/)
  assert.match(editorial, /renderDomainFlow/)
  assert.match(editorial, /재물·보상 흐름/)
  assert.match(editorial, /일·직장 흐름/)
  assert.match(editorial, /관계·연애 흐름/)
  assert.match(editorial, /renderedDomainFlows/)
  assert.match(editorial, /updateLifeFlowMap/)
  assert.match(editorial, /운세 점수 아님/)
  assert.match(editorial, /summary\.after\(renderLifeFlowMap\(\)\)/, '대운 그래프는 한눈에 보기 다음에 보여야 한다')
  assert.match(editorial, /'나의 대운 흐름'/)
  assert.match(styles, /review-life-flow/)
  assert.match(styles, /\[data-umsh-service-top\] \.umsh-service-shell/)
  assert.match(styles, /border-bottom: 0/)
  assert.match(styles, /review-daewoon-rail/)
  assert.match(styles, /review-daewoon-segment\.is-current/)
  assert.match(styles, /review-life-curve-svg/)
  assert.match(styles, /review-life-current-callout/)
  assert.match(styles, /review-life-connection/)
  assert.match(styles, /review-domain-flow-svg/)
  assert.match(styles, /reading-card > summary::after/)
  assert.match(styles, /content: '펼치기 \+'/)
  assert.match(styles, /reading-card\[open\] > summary::after/)
  assert.match(styles, /content: '접기 −'/)
  assert.match(styles, /prefers-reduced-motion/)
})
