import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { getCorpusSnapshot } from '../../src/rag/corpus-registry.js'
import { retrieveRagChunks } from '../../src/rag/retriever.js'
import { buildTemplateSajuReport, reviewGeneratedSajuReportSection, sectionPrompt } from '../../src/report/report-generator.js'
import { analyzeSaju } from '../../src/saju/analyzer.js'
import type { BirthInput, CorpusSnapshot, SajuReportContext } from '../../src/types/index.js'

const root = process.cwd()
const oldPath = 'tone-v2/corpus/couple-signal-service.json'
const newPath = 'tone-v2/corpus/releases/couple-signal-service-2.1.0.json'
const oldMarker = '표현의 양은 시기와 체력에 따라 쉽게 줄어든다'
const newMarker = '관계 신호는 사용자가 확인한 행동과 직접 들은 말로만 설명한다'
const birth: BirthInput = { year: 1985, month: 3, day: 20, hour: 9, gender: 'male', calendar: 'solar' }
const context: SajuReportContext = { serviceKey: 'couple_signal', concern: '교제 중 · 연락 간격이 달라졌지만 이유는 아직 직접 확인하지 않았어요.' }
const hashFile = (path: string) => createHash('sha256').update(readFileSync(join(root, 'data', path), 'utf8')).digest('hex')
function oldSnapshot(): CorpusSnapshot { const current = getCorpusSnapshot(); return { ...current, registryVersion: 'tone-v2.2.0.14', fingerprint: 'old-couple-signal', activePacks: current.activePacks.map((pack) => pack.id === 'couple-signal-service' ? { ...pack, path: oldPath, version: '2.0.0', contentHash: hashFile(oldPath).slice(0, 16) } : pack) } }

describe('[TASK P05] couple_signal corpus/RAG release candidate', () => {
  it('activates reviewed 2.1.0 and retains 2.0.0', () => { const pack = getCorpusSnapshot().activePacks.find((item) => item.id === 'couple-signal-service'); assert.equal(pack?.version, '2.1.0'); assert.equal(pack?.path, newPath); assert.doesNotThrow(() => readFileSync(join(root, 'data', oldPath))); assert.equal(pack?.contentHash, hashFile(newPath).slice(0, 16)) })
  it('records twelve semantic-review passes', () => { const review = JSON.parse(readFileSync(join(root, 'tone-v2/corpus-review/couple-signal-2.1.0.json'), 'utf8')); assert.equal(review.status, 'approved'); assert.equal(review.sourcePath, `data/${newPath}`); assert.equal(review.sourceSha256, hashFile(newPath)); assert.equal(review.sampleOutputsIngested, false); assert.equal(review.blocks.length, 12); assert.deepEqual(review.blocks.map((item: any) => item.id), Array.from({ length: 12 }, (_, index) => `sig-${String(index + 1).padStart(3, '0')}`)); assert.ok(review.blocks.every((block: any) => block.status === 'pass' && Object.values(block.checks).every(Boolean))) })
  it('enforces fact, mind, fidelity, monitoring, numeric and safety boundaries', () => { const pack = JSON.parse(readFileSync(join(root, 'data', newPath), 'utf8')); const blocks = pack.knowledgeBlocks; const text = blocks.map((block: any) => [block.concept, block.condition, block.interpretation, ...block.real_world_pattern, block.risk, block.opportunity, block.advice, block.forbidden_generalization].join(' ')).join(' '); const guidance = blocks.map((block: any) => [block.concept, block.interpretation, ...block.real_world_pattern, block.opportunity, block.advice].join(' ')).join(' '); assert.equal(blocks.length, 12); assert.equal(new Set(blocks.map((block: any) => block.interpretation)).size, 12); assert.ok(blocks.every((block: any) => block.real_world_pattern.every((item: string) => item.startsWith('가상 사례:')))); assert.ok(blocks.every((block: any) => /사용자가 확인한 행동과 직접 들은 말/.test(block.condition) && /계산값은 상징적 질문/.test(block.condition) && /알 수 없음/.test(block.condition))); assert.doesNotMatch(text, /현재 항목과 계산값이 직접 연결될 때만 사용한다/); assert.match(text, new RegExp(newMarker)); assert.match(text, /연락 거부/); assert.match(text, /위협|폭력/); assert.match(text, /감시|무단/); assert.doesNotMatch(guidance, /몇 시간|며칠|세 번|다음 날|하루|일주일|반드시/); assert.doesNotMatch(guidance, /마음이 떠났다|바람을 피운다|외도.*확정|관계는.*회복|답 대신 방어가 돌아온다/) })
  it('separates active and stored retrieval', () => { const analysis = analyzeSaju(birth); const active = retrieveRagChunks('관계 연락 표현 약속 신호 확인', analysis, 30, context); const old = retrieveRagChunks('관계 연락 표현 약속 신호 확인', analysis, 30, context, oldSnapshot()); const activeText = active.map((item) => item.content).join('\n'); const oldText = old.map((item) => item.content).join('\n'); assert.ok(active.some((item) => item.domain === 'couple_signal_service')); assert.ok(old.some((item) => item.domain === 'couple_signal_service')); assert.match(activeText, new RegExp(newMarker)); assert.doesNotMatch(activeText, new RegExp(oldMarker)); assert.match(oldText, new RegExp(oldMarker)); assert.doesNotMatch(oldText, new RegExp(newMarker)) })
  it('fails closed on stored hash mismatch', () => { const snapshot = oldSnapshot(); snapshot.activePacks = snapshot.activePacks.map((pack) => pack.id === 'couple-signal-service' ? { ...pack, contentHash: '0000000000000000' } : pack); assert.throws(() => retrieveRagChunks('관계 신호', analyzeSaju(birth), 30, context, snapshot), /Corpus snapshot hash mismatch: couple-signal-service/) })
  it('builds prompts from stored snapshot', () => { const analysis = analyzeSaju(birth); const section = buildTemplateSajuReport(analysis, birth, context).sections[0]; assert.ok(section); const active = sectionPrompt(analysis, birth, context, section).map((item) => item.content).join('\n'); const old = sectionPrompt(analysis, birth, context, section, [], oldSnapshot()).map((item) => item.content).join('\n'); assert.match(active, new RegExp(newMarker)); assert.doesNotMatch(active, new RegExp(oldMarker)); assert.match(old, new RegExp(oldMarker)); assert.doesNotMatch(old, new RegExp(newMarker)) })
  it('reviews saved prose against stored snapshot', () => { const analysis = analyzeSaju(birth); const section = buildTemplateSajuReport(analysis, birth, context).sections[0]; assert.ok(section); const common = { analysis, birth, context, section, hook: '확인된 행동과 모르는 마음을 구분해요.', interpretation: `${oldMarker}.` }; const issue = '코퍼스 문장을 복사하지 말고 현재 질문과 근거에 맞는 새 문장으로 다시 쓰세요.'; assert.ok(!reviewGeneratedSajuReportSection(common).issues.includes(issue)); assert.ok(reviewGeneratedSajuReportSection({ ...common, corpusSnapshot: oldSnapshot() }).issues.includes(issue)) })
  it('binds a truthful reversible local candidate', () => { const manifest = JSON.parse(readFileSync(join(root, 'tone-v2/releases/couple-signal-2.1.0.json'), 'utf8')); assert.equal(manifest.state, 'candidate'); assert.equal(manifest.deployed, false); assert.equal(manifest.serviceKey, 'couple_signal'); assert.equal(manifest.generationEvidence, null); assert.match(manifest.generationEvidenceReason, /no provider evaluation/i); assert.deepEqual(manifest.corpus.candidate, { path: `data/${newPath}`, version: '2.1.0', sha256: hashFile(newPath) }); assert.deepEqual(manifest.corpus.previous, { path: `data/${oldPath}`, version: '2.0.0', sha256: hashFile(oldPath) }); assert.equal(manifest.attachment.newReportsOnly, true); assert.equal(manifest.attachment.customerRecordMutation, false); assert.equal(manifest.rollback.strategy, 'registry_only'); assert.equal(manifest.verificationEvidence, 'tone-v2/evaluations/P05-couple-signal-corpus-rag-release-candidate-20260913.json'); assert.ok(Object.values(manifest.gates).every((value) => value !== 'pending')) })
})
