import { createHash } from 'node:crypto'; import { readFileSync } from 'node:fs'; import { join } from 'node:path'; import assert from 'node:assert/strict'; import { describe,it } from 'node:test'
import { getCorpusSnapshot } from '../../src/rag/corpus-registry.js'; import { retrieveRagChunks } from '../../src/rag/retriever.js'; import { buildTemplateSajuReport,reviewGeneratedSajuReportSection,sectionPrompt } from '../../src/report/report-generator.js'; import { analyzeSaju } from '../../src/saju/analyzer.js'; import type { BirthInput,CorpusSnapshot,SajuReportContext } from '../../src/types/index.js'
const root=process.cwd(),oldPath='tone-v2/corpus/home-fit-service.json',newPath='tone-v2/corpus/releases/home-fit-service-2.1.0.json',oldMarker='터는 분위기 감상이 아니라 집이 놓인 바닥의 성격이에요',newMarker='터 유사도와 경사값은 서버가 제공할 때만 측정값이며 집의 안전이나 가치를 증명하지 않는다'
const birth:BirthInput={year:1985,month:3,day:20,hour:9,gender:'male',calendar:'solar'},context:SajuReportContext={serviceKey:'home_fit',concern:'측정된 집 조건과 아직 확인하지 않은 조건을 구분하고 싶어요.'},hashFile=(p:string)=>createHash('sha256').update(readFileSync(join(root,'data',p),'utf8')).digest('hex')
function oldSnapshot():CorpusSnapshot{const c=getCorpusSnapshot();return{...c,registryVersion:'tone-v2.2.0.10',fingerprint:'old-home-fit',activePacks:c.activePacks.map(p=>p.id==='home-fit-service'?{...p,path:oldPath,version:'2.0.0',contentHash:hashFile(oldPath).slice(0,16)}:p)}}
describe('[TASK P05] home_fit corpus/RAG release candidate',()=>{
 it('activates reviewed 2.1.0 and retains 2.0.0',()=>{const p=getCorpusSnapshot().activePacks.find(x=>x.id==='home-fit-service');assert.equal(p?.version,'2.1.0');assert.equal(p?.path,newPath);assert.doesNotThrow(()=>readFileSync(join(root,'data',oldPath)));assert.equal(p?.contentHash,hashFile(newPath).slice(0,16))})
 it('records twelve semantic-review passes',()=>{const r=JSON.parse(readFileSync(join(root,'tone-v2/corpus-review/home-fit-2.1.0.json'),'utf8'));assert.equal(r.status,'approved');assert.equal(r.sourcePath,`data/${newPath}`);assert.equal(r.sourceSha256,hashFile(newPath));assert.equal(r.sampleOutputsIngested,false);assert.equal(r.blocks.length,12);assert.deepEqual(r.blocks.map((x:any)=>x.id),Array.from({length:12},(_,i)=>`hfit-${String(i+1).padStart(3,'0')}`));assert.ok(r.blocks.every((b:any)=>b.status==='pass'&&Object.values(b.checks).every(Boolean)))})
 it('enforces observation, measurement, unknown, symbolic and hypothetical boundaries',()=>{const p=JSON.parse(readFileSync(join(root,'data',newPath),'utf8')),blocks=p.knowledgeBlocks,t=blocks.map((b:any)=>[b.condition,b.interpretation,...b.real_world_pattern,b.risk,b.opportunity,b.advice,b.forbidden_generalization].join(' ')).join(' ');assert.equal(blocks.length,12);assert.ok(blocks.every((b:any)=>b.real_world_pattern.every((x:string)=>x.startsWith('가상 사례:'))));assert.ok(blocks.every((b:any)=>/사용자 입력 또는 서버 제공 측정값/.test(b.condition)&&/미측정 항목은 알 수 없음/.test(b.condition)&&/상징적 질문/.test(b.condition)));assert.doesNotMatch(t,/현재 항목과 계산값이 직접 연결될 때만 사용한다/);assert.match(t,/안전|사고/);assert.match(t,/건강|질병/);assert.match(t,/재산 가치|재물 손실/);assert.match(t,/관계 파탄/);assert.match(t,/이사|계약/);assert.match(t,/전문가/);assert.doesNotMatch(t,/수치가 부족하면 비슷한 터/);assert.doesNotMatch(t,/반드시 명당|이 집 때문에 질병|재산 가치가 오른다/)})
 it('separates active and stored retrieval',()=>{const a=analyzeSaju(birth),x=retrieveRagChunks('터 유사도 경사 지형 받침감',a,20,context),y=retrieveRagChunks('터 유사도 경사 지형 받침감',a,20,context,oldSnapshot()),xt=x.map(v=>v.content).join('\n'),yt=y.map(v=>v.content).join('\n');assert.ok(x.some(v=>v.domain==='home_fit_service'));assert.ok(y.some(v=>v.domain==='home_fit_service'));assert.match(xt,new RegExp(newMarker));assert.doesNotMatch(xt,new RegExp(oldMarker));assert.match(yt,new RegExp(oldMarker));assert.doesNotMatch(yt,new RegExp(newMarker))})
 it('fails closed on stored hash mismatch',()=>{const s=oldSnapshot();s.activePacks=s.activePacks.map(p=>p.id==='home-fit-service'?{...p,contentHash:'0000000000000000'}:p);assert.throws(()=>retrieveRagChunks('터 유사도',analyzeSaju(birth),20,context,s),/Corpus snapshot hash mismatch: home-fit-service/)})
 it('builds prompts from stored snapshot',()=>{const a=analyzeSaju(birth),s=buildTemplateSajuReport(a,birth,context).sections[1];assert.ok(s);const x=sectionPrompt(a,birth,context,s).map(v=>v.content).join('\n'),y=sectionPrompt(a,birth,context,s,[],oldSnapshot()).map(v=>v.content).join('\n');assert.match(x,new RegExp(newMarker));assert.doesNotMatch(x,new RegExp(oldMarker));assert.match(y,new RegExp(oldMarker));assert.doesNotMatch(y,new RegExp(newMarker))})
 it('reviews saved prose against stored snapshot',()=>{const a=analyzeSaju(birth),s=buildTemplateSajuReport(a,birth,context).sections[1];assert.ok(s);const c={analysis:a,birth,context,section:s,hook:'측정값과 상징을 구분해요.',interpretation:`${oldMarker}.`},i='코퍼스 문장을 복사하지 말고 현재 질문과 근거에 맞는 새 문장으로 다시 쓰세요.';assert.ok(!reviewGeneratedSajuReportSection(c).issues.includes(i));assert.ok(reviewGeneratedSajuReportSection({...c,corpusSnapshot:oldSnapshot()}).issues.includes(i))})
 it('binds truthful candidate and rollback',()=>{const m=JSON.parse(readFileSync(join(root,'tone-v2/releases/home-fit-2.1.0.json'),'utf8'));assert.equal(m.state,'candidate');assert.equal(m.deployed,false);assert.equal(m.serviceKey,'home_fit');assert.equal(m.generationEvidence,null);assert.deepEqual(m.corpus.candidate,{path:`data/${newPath}`,version:'2.1.0',sha256:hashFile(newPath)});assert.deepEqual(m.corpus.previous,{path:`data/${oldPath}`,version:'2.0.0',sha256:hashFile(oldPath)});assert.equal(m.attachment.newReportsOnly,true);assert.equal(m.rollback.strategy,'registry_only');assert.equal(m.verificationEvidence,'tone-v2/evaluations/P05-home-fit-corpus-rag-release-candidate-20260913.json');assert.ok(Object.values(m.gates).every(v=>v!=='pending'))})
})
