import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { getCorpusSnapshot } from '../../src/rag/corpus-registry.js'
import { retrieveRagChunks } from '../../src/rag/retriever.js'
import { buildTemplateSajuReport, reviewGeneratedSajuReportSection, sectionPrompt } from '../../src/report/report-generator.js'
import { analyzeSaju } from '../../src/saju/analyzer.js'
import type { BirthInput, CorpusSnapshot, SajuReportContext } from '../../src/types/index.js'

const root = process.cwd()
const oldPath = 'tone-v2/corpus/job-choice-service.json'
const newPath = 'tone-v2/corpus/releases/job-choice-service-2.1.0.json'
const oldMarker = '같은 직무명이라도 회사가 다르면 하는 일이 전혀 다르다. 무엇을 맡는지, 누구에게 보고하는지, 무엇으로 평가받는지를 물으면 직무명보다 정확한 답이 나온다.'
const newMarker = '직장 선택은 사용자가 확인한 오퍼·근로 조건과 서버가 계산한 사주 값을 비교 질문으로 번역할 뿐 회사의 숨은 조건이나 채용·경력 결과를 증명하지 않는다'
const birth: BirthInput = { year: 1990, month: 4, day: 12, hour: 12, gender: 'female', calendar: 'solar' }
const context: SajuReportContext = { serviceKey: 'job_choice', work: '확인된 기획 역할', concern: '제안서에 적힌 조건을 비교하고 싶고 조직 문화와 실제 업무 범위는 아직 확인하지 않았어요.' }
const hashFile = (path: string) => createHash('sha256').update(readFileSync(join(root, 'data', path), 'utf8')).digest('hex')
function oldSnapshot(): CorpusSnapshot { const current = getCorpusSnapshot(); return { ...current, registryVersion: 'tone-v2.2.0.18', fingerprint: 'old-job-choice', activePacks: current.activePacks.map((pack) => pack.id === 'job-choice-service' ? { ...pack, path: oldPath, version: '2.0.0', contentHash: hashFile(oldPath).slice(0, 16) } : pack) } }

describe('[TASK P05] job_choice corpus/RAG release candidate', () => {
  it('activates reviewed 2.1.0 and retains 2.0.0', () => { const pack = getCorpusSnapshot().activePacks.find((item) => item.id === 'job-choice-service'); assert.equal(pack?.version, '2.1.0'); assert.equal(pack?.path, newPath); assert.doesNotThrow(() => readFileSync(join(root, 'data', oldPath))); assert.equal(pack?.contentHash, hashFile(newPath).slice(0, 16)) })
  it('records twelve semantic-review passes', () => { const review = JSON.parse(readFileSync(join(root, 'tone-v2/corpus-review/job-choice-2.1.0.json'), 'utf8')); assert.equal(review.status, 'approved'); assert.equal(review.sourcePath, `data/${newPath}`); assert.equal(review.sourceSha256, hashFile(newPath)); assert.equal(review.sampleOutputsIngested, false); assert.equal(review.blocks.length, 12); assert.deepEqual(review.blocks.map((item: any) => item.id), Array.from({ length: 12 }, (_, index) => `job-${String(index + 1).padStart(3, '0')}`)); assert.ok(review.blocks.every((block: any) => block.status === 'pass' && Object.values(block.checks).every(Boolean))) })
  it('enforces offer-document, calculation, company-reality, numeric and professional boundaries', () => { const pack = JSON.parse(readFileSync(join(root, 'data', newPath), 'utf8')); const blocks = pack.knowledgeBlocks; const text = blocks.map((block: any) => [block.topic, block.concept, block.condition, block.interpretation, ...block.real_world_pattern, block.risk, block.opportunity, block.advice, block.forbidden_generalization].join(' ')).join(' '); const guidance = blocks.map((block: any) => [block.topic, block.concept, block.interpretation, ...block.real_world_pattern, block.opportunity, block.advice].join(' ')).join(' '); assert.equal(blocks.length, 12); assert.equal(new Set(blocks.map((block: any) => block.interpretation)).size, 12); assert.equal(new Set(blocks.map((block: any) => block.topic)).size, 12); assert.ok(blocks.every((block: any) => block.real_world_pattern.every((item: string) => item.startsWith('가상 사례:')))); assert.ok(blocks.every((block: any) => /사용자가 확인한/.test(block.condition) && /서버가 계산한/.test(block.condition) && /알 수 없음/.test(block.condition))); assert.doesNotMatch(text, /현재 항목과 계산값이 직접 연결될 때만 사용한다/); assert.match(text, new RegExp(newMarker)); assert.match(text, /근로계약|오퍼 문서|제안서/); assert.match(text, /관록궁.*관점|궁 이름.*관점/); assert.match(text, /법률|노무|재무|의료|전문/); assert.doesNotMatch(guidance, /세 줄|하나뿐|첫 달|여섯 달|몇 달|월 단위|이번 주|최소 며칠|주말 한 번|오늘 하나|질문 하나|가장 중요한 하나|요구를 하나|여러 개/); assert.doesNotMatch(guidance, /마음 한쪽이 계속 걸린다|남의 평가에서 온 것이었다|실제로는 다른 일을 한다|소모가 크다|매일의 피로를 만든다|좋은 사람들끼리도 자주 부딪힌다|체감은 불안정|실수령은 줄어든다|성장이 눈에 보인다|야근의 다른 이름|소모가 쌓인다|피로가 덜하다|한 주를 무너뜨린다|대체로 조율 여지가 있고|관계만 어색해진다|우선순위를 정한 사람이 협상에서 얻는다/) })
  it('separates active and stored retrieval', () => { const analysis = analyzeSaju(birth); const active = retrieveRagChunks('직장 선택 오퍼 조건 비교 결정', analysis, 40, context); const old = retrieveRagChunks('직장 선택 오퍼 조건 비교 결정', analysis, 40, context, oldSnapshot()); const activeText = active.map((item) => item.content).join('\n'); const oldText = old.map((item) => item.content).join('\n'); assert.ok(active.some((item) => item.domain === 'job_choice_service')); assert.ok(old.some((item) => item.domain === 'job_choice_service')); assert.match(activeText, new RegExp(newMarker)); assert.doesNotMatch(activeText, new RegExp(oldMarker)); assert.match(oldText, new RegExp(oldMarker)); assert.doesNotMatch(oldText, new RegExp(newMarker)) })
  it('fails closed on stored hash mismatch', () => { const snapshot = oldSnapshot(); snapshot.activePacks = snapshot.activePacks.map((pack) => pack.id === 'job-choice-service' ? { ...pack, contentHash: '0000000000000000' } : pack); assert.throws(() => retrieveRagChunks('직장 선택 오퍼', analyzeSaju(birth), 40, context, snapshot), /Corpus snapshot hash mismatch: job-choice-service/) })
  it('builds prompts from stored snapshot', () => { const analysis = analyzeSaju(birth); const section = buildTemplateSajuReport(analysis, birth, context).sections[0]; assert.ok(section); const active = sectionPrompt(analysis, birth, context, section).map((item) => item.content).join('\n'); const old = sectionPrompt(analysis, birth, context, section, [], oldSnapshot()).map((item) => item.content).join('\n'); assert.match(active, new RegExp(newMarker)); assert.doesNotMatch(active, new RegExp(oldMarker)); assert.match(old, new RegExp(oldMarker)); assert.doesNotMatch(old, new RegExp(newMarker)) })
  it('reviews saved prose against stored snapshot', () => { const analysis = analyzeSaju(birth); const section = buildTemplateSajuReport(analysis, birth, context).sections[0]; assert.ok(section); const common = { analysis, birth, context, section, hook: '확인된 오퍼 조건과 미확인 영역을 분리합니다.', interpretation: oldMarker }; const issue = '코퍼스 문장을 복사하지 말고 현재 질문과 근거에 맞는 새 문장으로 다시 쓰세요.'; assert.ok(!reviewGeneratedSajuReportSection(common).issues.includes(issue)); assert.ok(reviewGeneratedSajuReportSection({ ...common, corpusSnapshot: oldSnapshot() }).issues.includes(issue)) })
  it('binds a truthful reversible local candidate', () => { const manifest = JSON.parse(readFileSync(join(root, 'tone-v2/releases/job-choice-2.1.0.json'), 'utf8')); assert.equal(manifest.state, 'candidate'); assert.equal(manifest.deployed, false); assert.equal(manifest.serviceKey, 'job_choice'); assert.equal(manifest.generationEvidence, null); assert.match(manifest.generationEvidenceReason, /no provider evaluation/i); assert.deepEqual(manifest.corpus.candidate, { path: `data/${newPath}`, version: '2.1.0', sha256: hashFile(newPath) }); assert.deepEqual(manifest.corpus.previous, { path: `data/${oldPath}`, version: '2.0.0', sha256: hashFile(oldPath) }); assert.equal(manifest.attachment.newReportsOnly, true); assert.equal(manifest.attachment.customerRecordMutation, false); assert.equal(manifest.rollback.strategy, 'registry_only'); assert.equal(manifest.verificationEvidence, 'tone-v2/evaluations/P05-job-choice-corpus-rag-release-candidate-20260913.json'); assert.ok(Object.values(manifest.gates).every((value) => value !== 'pending')) })
})
