import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { getCorpusSnapshot } from '../../src/rag/corpus-registry.js'
import { retrieveRagChunks } from '../../src/rag/retriever.js'
import { buildTemplateSajuReport, reviewGeneratedSajuReportSection, sectionPrompt } from '../../src/report/report-generator.js'
import { analyzeSaju } from '../../src/saju/analyzer.js'
import type { BirthInput, CorpusSnapshot, SajuReportContext } from '../../src/types/index.js'

const root = process.cwd(), oldPath = 'tone-v2/corpus/love-mind-service.json', newPath = 'tone-v2/corpus/releases/love-mind-service-2.1.0.json'
const oldMarker = '연락과 약속은 관심을 살피는 단서지만 마음의 증명은 아니다'
const newMarker = '관찰된 연락과 약속은 행동 사실이지만 상대의 감정이나 의도를 증명하지 않는다'
const birth: BirthInput = { year: 1985, month: 3, day: 20, hour: 9, gender: 'male', calendar: 'solar' }
const context: SajuReportContext = { serviceKey: 'love_mind', relationship: '연락은 오지만 다음 약속은 정하지 않은 상태', concern: '관찰한 행동과 아직 모르는 마음을 구분하고 싶어요.' }
const hashFile = (path: string) => createHash('sha256').update(readFileSync(join(root, 'data', path), 'utf8')).digest('hex')
function oldSnapshot(): CorpusSnapshot { const current = getCorpusSnapshot(); return { ...current, registryVersion: 'tone-v2.2.0.7', fingerprint: 'test-old-love-mind-snapshot', activePacks: current.activePacks.map((p) => p.id === 'love-mind-service' ? { ...p, path: oldPath, version: '2.0.0', contentHash: hashFile(oldPath).slice(0, 16) } : p) } }

describe('[TASK P05] love_mind corpus/RAG release candidate', () => {
  it('activates reviewed 2.1.0 and retains 2.0.0', () => { const p = getCorpusSnapshot().activePacks.find((x) => x.id === 'love-mind-service'); assert.equal(p?.version, '2.1.0'); assert.equal(p?.path, newPath); assert.doesNotThrow(() => readFileSync(join(root, 'data', oldPath))); assert.equal(p?.contentHash, hashFile(newPath).slice(0, 16)) })
  it('records one explicit semantic-review pass', () => { const r = JSON.parse(readFileSync(join(root, 'tone-v2/corpus-review/love-mind-2.1.0.json'), 'utf8')); assert.equal(r.status, 'approved'); assert.equal(r.sourcePath, `data/${newPath}`); assert.equal(r.sourceSha256, hashFile(newPath)); assert.equal(r.sampleOutputsIngested, false); assert.deepEqual(r.blocks.map((x: any) => x.id), ['mind-001']); assert.ok(r.blocks.every((b: any) => b.status === 'pass' && Object.values(b.checks).every(Boolean))) })
  it('enforces observation, mind, refusal, safety and hypothetical boundaries', () => { const p = JSON.parse(readFileSync(join(root, 'data', newPath), 'utf8')), b = p.knowledgeBlocks[0]; const t = [b.condition,b.interpretation,...b.real_world_pattern,b.risk,b.opportunity,b.advice,b.forbidden_generalization].join(' '); const g=[b.interpretation,...b.real_world_pattern,b.opportunity,b.advice].join(' '); assert.equal(p.release.sampleOutputsIngested,false); assert.ok(b.real_world_pattern.every((x:string)=>x.startsWith('가상 사례:'))); assert.match(b.condition,/serviceKey.*사용자가 직접 관찰하거나 전달받은/); assert.match(t,/명시적 거절/); assert.match(t,/위협|강압|스토킹|폭력/); assert.match(b.forbidden_generalization,/연락이나 무응답만으로/); assert.doesNotMatch(t,/\d+\s*(?:분|시간|일|주|개월|년|번|가지|개)\b/); assert.doesNotMatch(g,/나를 사랑한다|곧 연락한다|재회한다|마음이 확실하다/) })
  it('separates active and stored snapshot retrieval', () => { const a=analyzeSaju(birth), active=retrieveRagChunks('상대방 마음 연락 약속 관심 행동 확인',a,20,context), old=retrieveRagChunks('상대방 마음 연락 약속 관심 행동 확인',a,20,context,oldSnapshot()); const at=active.map(x=>x.content).join('\n'), ot=old.map(x=>x.content).join('\n'); assert.ok(active.some(x=>x.domain==='love_mind_service')); assert.ok(old.some(x=>x.domain==='love_mind_service')); assert.match(at,new RegExp(newMarker)); assert.doesNotMatch(at,new RegExp(oldMarker)); assert.match(ot,new RegExp(oldMarker)); assert.doesNotMatch(ot,new RegExp(newMarker)) })
  it('fails closed on stored hash mismatch', () => { const s=oldSnapshot(); s.activePacks=s.activePacks.map(p=>p.id==='love-mind-service'?{...p,contentHash:'0000000000000000'}:p); assert.throws(()=>retrieveRagChunks('상대방 마음 연락',analyzeSaju(birth),20,context,s),/Corpus snapshot hash mismatch: love-mind-service/) })
  it('builds prompts from the report snapshot', () => { const a=analyzeSaju(birth), section=buildTemplateSajuReport(a,birth,context).sections[0]; assert.ok(section); const at=sectionPrompt(a,birth,context,section).map(x=>x.content).join('\n'), ot=sectionPrompt(a,birth,context,section,[],oldSnapshot()).map(x=>x.content).join('\n'); assert.match(at,new RegExp(newMarker)); assert.doesNotMatch(at,new RegExp(oldMarker)); assert.match(ot,new RegExp(oldMarker)); assert.doesNotMatch(ot,new RegExp(newMarker)) })
  it('reviews saved prose against the stored snapshot', () => { const a=analyzeSaju(birth), section=buildTemplateSajuReport(a,birth,context).sections[0]; assert.ok(section); const common={analysis:a,birth,context,section,hook:'확인된 행동과 모르는 마음을 구분해요.',interpretation:`${oldMarker}.`}; const issue='코퍼스 문장을 복사하지 말고 현재 질문과 근거에 맞는 새 문장으로 다시 쓰세요.'; assert.ok(!reviewGeneratedSajuReportSection(common).issues.includes(issue)); assert.ok(reviewGeneratedSajuReportSection({...common,corpusSnapshot:oldSnapshot()}).issues.includes(issue)) })
  it('binds a truthful candidate and rollback', () => { const m=JSON.parse(readFileSync(join(root,'tone-v2/releases/love-mind-2.1.0.json'),'utf8')); assert.equal(m.state,'candidate'); assert.equal(m.deployed,false); assert.equal(m.serviceKey,'love_mind'); assert.equal(m.generationEvidence,null); assert.deepEqual(m.corpus.candidate,{path:`data/${newPath}`,version:'2.1.0',sha256:hashFile(newPath)}); assert.deepEqual(m.corpus.previous,{path:`data/${oldPath}`,version:'2.0.0',sha256:hashFile(oldPath)}); assert.equal(m.attachment.newReportsOnly,true); assert.equal(m.attachment.storedSnapshotRequired,true); assert.equal(m.rollback.strategy,'registry_only'); assert.equal(m.verificationEvidence,'tone-v2/evaluations/P05-love-mind-corpus-rag-release-candidate-20260913.json'); assert.ok(Object.values(m.gates).every(v=>v!=='pending')) })
})
