import { createHash } from 'node:crypto'; import { readFileSync } from 'node:fs'; import { join } from 'node:path'; import assert from 'node:assert/strict'; import { describe,it } from 'node:test'
import { getCorpusSnapshot } from '../../src/rag/corpus-registry.js'; import { retrieveRagChunks } from '../../src/rag/retriever.js'; import { buildTemplateSajuReport,reviewGeneratedSajuReportSection,sectionPrompt } from '../../src/report/report-generator.js'; import { analyzeSaju } from '../../src/saju/analyzer.js'; import type { BirthInput,CorpusSnapshot,SajuReportContext } from '../../src/types/index.js'
const root=process.cwd(),oldPath='tone-v2/corpus/love-spouse-service.json',newPath='tone-v2/corpus/releases/love-spouse-service-2.1.0.json',oldMarker='배우자궁은 특정 인물의 신원보다 가까운 관계에서 편안함과 책임을 어떻게 나누는지 보는 상징적 기준이다',newMarker='배우자궁과 계산값은 특정 인물의 신원이나 등장을 확인하지 않으며 동반자 조건을 점검하는 상징적 질문으로만 사용한다'
const birth:BirthInput={year:1985,month:3,day:20,hour:9,gender:'male',calendar:'solar'},context:SajuReportContext={serviceKey:'love_spouse',concern:'배우자 신원 예측보다 오래 함께할 관계 기준을 알고 싶어요.'},hashFile=(p:string)=>createHash('sha256').update(readFileSync(join(root,'data',p),'utf8')).digest('hex')
function oldSnapshot():CorpusSnapshot{const c=getCorpusSnapshot();return{...c,registryVersion:'tone-v2.2.0.9',fingerprint:'old-love-spouse',activePacks:c.activePacks.map(p=>p.id==='love-spouse-service'?{...p,path:oldPath,version:'2.0.0',contentHash:hashFile(oldPath).slice(0,16)}:p)}}
describe('[TASK P05] love_spouse corpus/RAG release candidate',()=>{
 it('activates reviewed 2.1.0 and retains 2.0.0',()=>{const p=getCorpusSnapshot().activePacks.find(x=>x.id==='love-spouse-service');assert.equal(p?.version,'2.1.0');assert.equal(p?.path,newPath);assert.doesNotThrow(()=>readFileSync(join(root,'data',oldPath)));assert.equal(p?.contentHash,hashFile(newPath).slice(0,16))})
 it('records one semantic-review pass',()=>{const r=JSON.parse(readFileSync(join(root,'tone-v2/corpus-review/love-spouse-2.1.0.json'),'utf8'));assert.equal(r.status,'approved');assert.equal(r.sourcePath,`data/${newPath}`);assert.equal(r.sourceSha256,hashFile(newPath));assert.equal(r.sampleOutputsIngested,false);assert.deepEqual(r.blocks.map((x:any)=>x.id),['spouse-001']);assert.ok(r.blocks.every((b:any)=>b.status==='pass'&&Object.values(b.checks).every(Boolean)))})
 it('enforces input, identity, timing, autonomy, safety and hypothetical boundaries',()=>{const p=JSON.parse(readFileSync(join(root,'data',newPath),'utf8')),b=p.knowledgeBlocks[0],t=[b.condition,b.interpretation,...b.real_world_pattern,b.risk,b.opportunity,b.advice,b.forbidden_generalization].join(' '),g=[b.interpretation,...b.real_world_pattern,b.opportunity,b.advice].join(' ');assert.ok(b.real_world_pattern.every((x:string)=>x.startsWith('가상 사례:')));assert.match(b.condition,/serviceKey.*사용자가 직접 밝힌 동반자 조건/);assert.match(t,/이름|나이|외모|직업|국적/);assert.match(t,/만남 시점|결혼 시점|등장/);assert.match(t,/거절|강압|통제|스토킹|폭력/);assert.match(b.forbidden_generalization,/사주나 배우자궁만으로/);assert.doesNotMatch(t,/\d+\s*(?:분|시간|일|주|개월|년|번|가지|개)\b/);assert.doesNotMatch(g,/반드시 나타난다|곧 만난다|결혼하게 된다|운명의 상대/)})
 it('separates active and stored retrieval',()=>{const a=analyzeSaju(birth),x=retrieveRagChunks('배우자 동반자 생활 책임 관계',a,20,context),y=retrieveRagChunks('배우자 동반자 생활 책임 관계',a,20,context,oldSnapshot()),xt=x.map(v=>v.content).join('\n'),yt=y.map(v=>v.content).join('\n');assert.ok(x.some(v=>v.domain==='love_spouse_service'));assert.ok(y.some(v=>v.domain==='love_spouse_service'));assert.match(xt,new RegExp(newMarker));assert.doesNotMatch(xt,new RegExp(oldMarker));assert.match(yt,new RegExp(oldMarker));assert.doesNotMatch(yt,new RegExp(newMarker))})
 it('fails closed on stored hash mismatch',()=>{const s=oldSnapshot();s.activePacks=s.activePacks.map(p=>p.id==='love-spouse-service'?{...p,contentHash:'0000000000000000'}:p);assert.throws(()=>retrieveRagChunks('배우자 동반자',analyzeSaju(birth),20,context,s),/Corpus snapshot hash mismatch: love-spouse-service/)})
 it('builds prompts from stored snapshot',()=>{const a=analyzeSaju(birth),s=buildTemplateSajuReport(a,birth,context).sections[0];assert.ok(s);const x=sectionPrompt(a,birth,context,s).map(v=>v.content).join('\n'),y=sectionPrompt(a,birth,context,s,[],oldSnapshot()).map(v=>v.content).join('\n');assert.match(x,new RegExp(newMarker));assert.doesNotMatch(x,new RegExp(oldMarker));assert.match(y,new RegExp(oldMarker));assert.doesNotMatch(y,new RegExp(newMarker))})
 it('reviews saved prose against stored snapshot',()=>{const a=analyzeSaju(birth),s=buildTemplateSajuReport(a,birth,context).sections[0];assert.ok(s);const c={analysis:a,birth,context,section:s,hook:'확인된 조건과 상징 질문을 구분해요.',interpretation:`${oldMarker}.`},i='코퍼스 문장을 복사하지 말고 현재 질문과 근거에 맞는 새 문장으로 다시 쓰세요.';assert.ok(!reviewGeneratedSajuReportSection(c).issues.includes(i));assert.ok(reviewGeneratedSajuReportSection({...c,corpusSnapshot:oldSnapshot()}).issues.includes(i))})
 it('binds truthful candidate and rollback',()=>{const m=JSON.parse(readFileSync(join(root,'tone-v2/releases/love-spouse-2.1.0.json'),'utf8'));assert.equal(m.state,'candidate');assert.equal(m.deployed,false);assert.equal(m.serviceKey,'love_spouse');assert.equal(m.generationEvidence,null);assert.deepEqual(m.corpus.candidate,{path:`data/${newPath}`,version:'2.1.0',sha256:hashFile(newPath)});assert.deepEqual(m.corpus.previous,{path:`data/${oldPath}`,version:'2.0.0',sha256:hashFile(oldPath)});assert.equal(m.attachment.newReportsOnly,true);assert.equal(m.rollback.strategy,'registry_only');assert.equal(m.verificationEvidence,'tone-v2/evaluations/P05-love-spouse-corpus-rag-release-candidate-20260913.json');assert.ok(Object.values(m.gates).every(v=>v!=='pending'))})
})
