import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { getCorpusSnapshot } from '../../src/rag/corpus-registry.js'
import { retrieveRagChunks } from '../../src/rag/retriever.js'
import { buildTemplateSajuReport, reviewGeneratedSajuReportSection, sectionPrompt } from '../../src/report/report-generator.js'
import { analyzeSaju } from '../../src/saju/analyzer.js'
import type { BirthInput, CorpusSnapshot, SajuReportContext } from '../../src/types/index.js'

const root = process.cwd()
const oldPath = 'tone-v2/corpus/lucky-color-service.json'
const newPath = 'tone-v2/corpus/releases/lucky-color-service-2.1.0.json'
const oldMarker = '많은 기운은 나쁜 것이 아니라 이미 충분한 것이고, 얇은 기운은 결함이 아니라 아직 덜 쓰인 자리입니다.'
const newMarker = '색과 물건은 서버가 계산한 오행을 생활 선택 질문으로 번역할 뿐 효능을 증명하지 않는다'
const birth: BirthInput = { year: 1985, month: 3, day: 20, hour: 9, gender: 'male', calendar: 'solar' }
const context: SajuReportContext = { serviceKey: 'lucky_color', concern: '선호 색이나 생활 공간 정보는 입력하지 않았어요.' }
const hashFile = (path: string) => createHash('sha256').update(readFileSync(join(root, 'data', path), 'utf8')).digest('hex')
function oldSnapshot(): CorpusSnapshot { const current = getCorpusSnapshot(); return { ...current, registryVersion: 'tone-v2.2.0.15', fingerprint: 'old-lucky-color', activePacks: current.activePacks.map((pack) => pack.id === 'lucky-color-service' ? { ...pack, path: oldPath, version: '2.0.0', contentHash: hashFile(oldPath).slice(0, 16) } : pack) } }

describe('[TASK P05] lucky_color corpus/RAG release candidate', () => {
  it('activates reviewed 2.1.0 and retains 2.0.0', () => { const pack = getCorpusSnapshot().activePacks.find((item) => item.id === 'lucky-color-service'); assert.equal(pack?.version, '2.1.0'); assert.equal(pack?.path, newPath); assert.doesNotThrow(() => readFileSync(join(root, 'data', oldPath))); assert.equal(pack?.contentHash, hashFile(newPath).slice(0, 16)) })
  it('records twenty-four semantic-review passes', () => { const review = JSON.parse(readFileSync(join(root, 'tone-v2/corpus-review/lucky-color-2.1.0.json'), 'utf8')); assert.equal(review.status, 'approved'); assert.equal(review.sourcePath, `data/${newPath}`); assert.equal(review.sourceSha256, hashFile(newPath)); assert.equal(review.sampleOutputsIngested, false); assert.equal(review.blocks.length, 24); assert.deepEqual(review.blocks.map((item: any) => item.id), Array.from({ length: 24 }, (_, index) => `lucky-${String(index + 1).padStart(3, '0')}`)); assert.ok(review.blocks.every((block: any) => block.status === 'pass' && Object.values(block.checks).every(Boolean))) })
  it('enforces calculation, efficacy, environment, numeric and professional boundaries', () => { const pack = JSON.parse(readFileSync(join(root, 'data', newPath), 'utf8')); const blocks = pack.knowledgeBlocks; const text = blocks.map((block: any) => [block.concept, block.condition, block.interpretation, ...block.real_world_pattern, block.risk, block.opportunity, block.advice, block.forbidden_generalization].join(' ')).join(' '); const guidance = blocks.map((block: any) => [block.concept, block.interpretation, ...block.real_world_pattern, block.opportunity, block.advice].join(' ')).join(' '); assert.equal(blocks.length, 24); assert.equal(new Set(blocks.map((block: any) => block.interpretation)).size, 24); assert.ok(blocks.every((block: any) => block.real_world_pattern.every((item: string) => item.startsWith('가상 사례:')))); assert.ok(blocks.every((block: any) => /서버가 계산한 오행/.test(block.condition) && /사용자가 확인한/.test(block.condition) && /알 수 없음/.test(block.condition))); assert.doesNotMatch(text, /현재 항목과 계산값이 직접 연결될 때만 사용한다/); assert.match(text, new RegExp(newMarker)); assert.match(text, /효능을 증명하지 않는다/); assert.match(text, /의료|전문/); assert.match(text, /식이 제한|수면 문제/); assert.doesNotMatch(guidance, /30분|한 시간|세 가지|며칠|일주일|한 끼|손바닥만큼|반드시/); assert.doesNotMatch(guidance, /잠드는 시간이 앞당겨|집중이 붙는다|하루의 방향을 잡는다|운이 안정|재물이 붙|액운|치료|질병이 낫/) })
  it('separates active and stored retrieval', () => { const analysis = analyzeSaju(birth); const active = retrieveRagChunks('오행 균형 용신 색 물건 생활 선택', analysis, 40, context); const old = retrieveRagChunks('오행 균형 용신 색 물건 생활 선택', analysis, 40, context, oldSnapshot()); const activeText = active.map((item) => item.content).join('\n'); const oldText = old.map((item) => item.content).join('\n'); assert.ok(active.some((item) => item.domain === 'lucky_color_service')); assert.ok(old.some((item) => item.domain === 'lucky_color_service')); assert.match(activeText, new RegExp(newMarker)); assert.doesNotMatch(activeText, new RegExp(oldMarker)); assert.match(oldText, new RegExp(oldMarker)); assert.doesNotMatch(oldText, new RegExp(newMarker)) })
  it('fails closed on stored hash mismatch', () => { const snapshot = oldSnapshot(); snapshot.activePacks = snapshot.activePacks.map((pack) => pack.id === 'lucky-color-service' ? { ...pack, contentHash: '0000000000000000' } : pack); assert.throws(() => retrieveRagChunks('오행 색 물건', analyzeSaju(birth), 40, context, snapshot), /Corpus snapshot hash mismatch: lucky-color-service/) })
  it('builds prompts from stored snapshot', () => { const analysis = analyzeSaju(birth); const section = buildTemplateSajuReport(analysis, birth, context).sections[0]; assert.ok(section); const active = sectionPrompt(analysis, birth, context, section).map((item) => item.content).join('\n'); const old = sectionPrompt(analysis, birth, context, section, [], oldSnapshot()).map((item) => item.content).join('\n'); assert.match(active, new RegExp(newMarker)); assert.doesNotMatch(active, new RegExp(oldMarker)); assert.match(old, new RegExp(oldMarker)); assert.doesNotMatch(old, new RegExp(newMarker)) })
  it('reviews saved prose against stored snapshot', () => { const analysis = analyzeSaju(birth); const section = buildTemplateSajuReport(analysis, birth, context).sections[0]; assert.ok(section); const common = { analysis, birth, context, section, hook: '계산과 생활 선택을 구분해요.', interpretation: oldMarker }; const issue = '코퍼스 문장을 복사하지 말고 현재 질문과 근거에 맞는 새 문장으로 다시 쓰세요.'; assert.ok(!reviewGeneratedSajuReportSection(common).issues.includes(issue)); assert.ok(reviewGeneratedSajuReportSection({ ...common, corpusSnapshot: oldSnapshot() }).issues.includes(issue)) })
  it('binds a truthful reversible local candidate', () => { const manifest = JSON.parse(readFileSync(join(root, 'tone-v2/releases/lucky-color-2.1.0.json'), 'utf8')); assert.equal(manifest.state, 'candidate'); assert.equal(manifest.deployed, false); assert.equal(manifest.serviceKey, 'lucky_color'); assert.equal(manifest.generationEvidence.path, 'tone-v2/evaluations/P04-lucky-color-full-outline-generation-20260913.json'); assert.equal(manifest.generationEvidence.containsProviderProse, false); assert.match(manifest.generationEvidence.recordSha256, /^[a-f0-9]{64}$/); assert.match(manifest.generationEvidence.acceptedProseSha256, /^[a-f0-9]{64}$/); assert.equal(manifest.visualEvidence.path, 'tone-v2/evaluations/P04-lucky-color-visual-render-evidence-20260913.json'); assert.equal(manifest.visualEvidence.desktop, 'pass_24_of_24'); assert.equal(manifest.visualEvidence.mobile, 'pass_24_of_24'); assert.equal(manifest.visualEvidence.print, 'pass_all_24_sections'); assert.equal(manifest.visualEvidence.containsProviderProse, false); assert.match(manifest.visualEvidence.sha256, /^[a-f0-9]{64}$/); assert.deepEqual(manifest.corpus.candidate, { path: `data/${newPath}`, version: '2.1.0', sha256: hashFile(newPath) }); assert.deepEqual(manifest.corpus.previous, { path: `data/${oldPath}`, version: '2.0.0', sha256: hashFile(oldPath) }); assert.equal(manifest.attachment.newReportsOnly, true); assert.equal(manifest.attachment.customerRecordMutation, false); assert.equal(manifest.rollback.strategy, 'registry_only'); assert.equal(manifest.verificationEvidence, 'tone-v2/evaluations/P05-lucky-color-corpus-rag-release-candidate-20260913.json'); assert.ok(Object.values(manifest.gates).every((value) => value !== 'pending')) })
})
