import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { getCorpusSnapshot } from '../../src/rag/corpus-registry.js'
import { retrieveRagChunks } from '../../src/rag/retriever.js'
import { buildTemplateSajuReport, reviewGeneratedSajuReportSection, sectionPrompt } from '../../src/report/report-generator.js'
import { analyzeSaju } from '../../src/saju/analyzer.js'
import type { BirthInput, CorpusSnapshot, SajuReportContext } from '../../src/types/index.js'

const root = process.cwd()
const oldPath = 'tone-v2/corpus/newyear-service.json'
const newPath = 'tone-v2/corpus/releases/newyear-service-2.1.0.json'
const oldRetrievalMarker = '세운은 한 해의 흐름이고 대운은 십 년의 판입니다.'
const oldPromptMarker = '하나가 끝나서 하나가 오는 것이 아니라, 결이 바뀌면서 맞는 사람이 달라지는 것입니다.'
const newMarker = '신년운세는 서버가 계산한 기준 연도·입춘·세운·월운·대운 값을 해석 질문으로 번역할 뿐 미래 사건이나 개인 상태를 증명하지 않는다'
const birth: BirthInput = { year: 1985, month: 3, day: 20, hour: 9, gender: 'male', calendar: 'solar' }
const context: SajuReportContext = { serviceKey: 'newyear_flow', concern: '2027년 관계 변화와 새 인연, 실제 일정과 결과는 아직 정하지 않았어요.' }
const hashFile = (path: string) => createHash('sha256').update(readFileSync(join(root, 'data', path), 'utf8')).digest('hex')
function oldSnapshot(): CorpusSnapshot { const current = getCorpusSnapshot(); return { ...current, registryVersion: 'tone-v2.2.0.16', fingerprint: 'old-newyear-flow', activePacks: current.activePacks.map((pack) => pack.id === 'newyear-service' ? { ...pack, path: oldPath, version: '2.0.0', contentHash: hashFile(oldPath).slice(0, 16) } : pack) } }

describe('[TASK P05] newyear_flow corpus/RAG release candidate', () => {
  it('activates reviewed 2.1.0 and retains 2.0.0', () => { const pack = getCorpusSnapshot().activePacks.find((item) => item.id === 'newyear-service'); assert.equal(pack?.version, '2.1.0'); assert.equal(pack?.path, newPath); assert.doesNotThrow(() => readFileSync(join(root, 'data', oldPath))); assert.equal(pack?.contentHash, hashFile(newPath).slice(0, 16)) })
  it('records ten semantic-review passes', () => { const review = JSON.parse(readFileSync(join(root, 'tone-v2/corpus-review/newyear-flow-2.1.0.json'), 'utf8')); assert.equal(review.status, 'approved'); assert.equal(review.sourcePath, `data/${newPath}`); assert.equal(review.sourceSha256, hashFile(newPath)); assert.equal(review.sampleOutputsIngested, false); assert.equal(review.blocks.length, 10); assert.deepEqual(review.blocks.map((item: any) => item.id), Array.from({ length: 10 }, (_, index) => `newyear-${String(index + 1).padStart(3, '0')}`)); assert.ok(review.blocks.every((block: any) => block.status === 'pass' && Object.values(block.checks).every(Boolean))) })
  it('enforces calculation, future, personal-state, numeric and professional boundaries', () => { const pack = JSON.parse(readFileSync(join(root, 'data', newPath), 'utf8')); const blocks = pack.knowledgeBlocks; const text = blocks.map((block: any) => [block.topic, block.concept, block.condition, block.interpretation, ...block.real_world_pattern, block.risk, block.opportunity, block.advice, block.forbidden_generalization].join(' ')).join(' '); const guidance = blocks.map((block: any) => [block.topic, block.concept, block.interpretation, ...block.real_world_pattern, block.opportunity, block.advice].join(' ')).join(' '); assert.equal(blocks.length, 10); assert.equal(new Set(blocks.map((block: any) => block.interpretation)).size, 10); assert.equal(new Set(blocks.map((block: any) => block.topic)).size, 10); assert.ok(blocks.every((block: any) => block.real_world_pattern.every((item: string) => item.startsWith('가상 사례:')))); assert.ok(blocks.every((block: any) => /서버가 계산한/.test(block.condition) && /사용자가 확인한/.test(block.condition) && /알 수 없음/.test(block.condition))); assert.doesNotMatch(text, /현재 항목과 계산값이 직접 연결될 때만 사용한다/); assert.match(text, new RegExp(newMarker)); assert.match(text, /미래 사건이나 개인 상태를 증명하지 않는다/); assert.match(text, /의료|법률|재무|전문/); assert.match(text, /출생 시각 미상/); assert.doesNotMatch(guidance, /2~3주|1~2년|3개월|분기마다|한 달에|두 칸|하나만|한 단어/); assert.doesNotMatch(guidance, /관계는 들어오는 인연과 정리되는 관계가 같은 해에 온다|지난해를 접지 않으면 새해의 힘을 먼저 쓴다|반드시|대개 같은 해에 같이 보입니다|실제로 남게 만듭니다|조건 하나만 바꿔도 결과가 달라집니다|몸이 신호를 보낸다|인생이 완전히 달라진다|특정 물건이나 색을 두면 새해 운이 열린다/) })
  it('separates active and stored retrieval', () => { const analysis = analyzeSaju(birth); const active = retrieveRagChunks('2027 세운 입춘 월운 대운 관계 흐름', analysis, 40, context); const old = retrieveRagChunks('2027 세운 입춘 월운 대운 관계 흐름', analysis, 40, context, oldSnapshot()); const activeText = active.map((item) => item.content).join('\n'); const oldText = old.map((item) => item.content).join('\n'); assert.ok(active.some((item) => item.domain === 'newyear_service')); assert.ok(old.some((item) => item.domain === 'newyear_service')); assert.match(activeText, new RegExp(newMarker)); assert.doesNotMatch(activeText, new RegExp(oldRetrievalMarker)); assert.match(oldText, new RegExp(oldRetrievalMarker)); assert.doesNotMatch(oldText, new RegExp(newMarker)) })
  it('fails closed on stored hash mismatch', () => { const snapshot = oldSnapshot(); snapshot.activePacks = snapshot.activePacks.map((pack) => pack.id === 'newyear-service' ? { ...pack, contentHash: '0000000000000000' } : pack); assert.throws(() => retrieveRagChunks('2027 세운 월운', analyzeSaju(birth), 40, context, snapshot), /Corpus snapshot hash mismatch: newyear-service/) })
  it('builds prompts from stored snapshot', () => { const analysis = analyzeSaju(birth); const section = buildTemplateSajuReport(analysis, birth, context).sections[0]; assert.ok(section); const active = sectionPrompt(analysis, birth, context, section).map((item) => item.content).join('\n'); const old = sectionPrompt(analysis, birth, context, section, [], oldSnapshot()).map((item) => item.content).join('\n'); assert.match(active, new RegExp(newMarker)); assert.doesNotMatch(active, new RegExp(oldPromptMarker)); assert.match(old, new RegExp(oldPromptMarker)); assert.doesNotMatch(old, new RegExp(newMarker)) })
  it('reviews saved prose against stored snapshot', () => { const analysis = analyzeSaju(birth); const section = buildTemplateSajuReport(analysis, birth, context).sections[0]; assert.ok(section); const common = { analysis, birth, context, section, hook: '계산과 미래 현실을 구분해요.', interpretation: oldPromptMarker }; const issue = '코퍼스 문장을 복사하지 말고 현재 질문과 근거에 맞는 새 문장으로 다시 쓰세요.'; assert.ok(!reviewGeneratedSajuReportSection(common).issues.includes(issue)); assert.ok(reviewGeneratedSajuReportSection({ ...common, corpusSnapshot: oldSnapshot() }).issues.includes(issue)) })
  it('binds a truthful reversible local candidate', () => { const manifest = JSON.parse(readFileSync(join(root, 'tone-v2/releases/newyear-flow-2.1.0.json'), 'utf8')); assert.equal(manifest.state, 'candidate'); assert.equal(manifest.deployed, false); assert.equal(manifest.serviceKey, 'newyear_flow'); assert.equal(manifest.generationEvidence.path, 'tone-v2/evaluations/P04-newyear-flow-full-outline-generation-20260913.json'); assert.equal(manifest.generationEvidence.containsProviderProse, false); assert.match(manifest.generationEvidence.recordSha256, /^[a-f0-9]{64}$/); assert.match(manifest.generationEvidence.acceptedProseSha256, /^[a-f0-9]{64}$/); assert.deepEqual(manifest.corpus.candidate, { path: `data/${newPath}`, version: '2.1.0', sha256: hashFile(newPath) }); assert.deepEqual(manifest.corpus.previous, { path: `data/${oldPath}`, version: '2.0.0', sha256: hashFile(oldPath) }); assert.equal(manifest.attachment.newReportsOnly, true); assert.equal(manifest.attachment.customerRecordMutation, false); assert.equal(manifest.rollback.strategy, 'registry_only'); assert.equal(manifest.verificationEvidence, 'tone-v2/evaluations/P05-newyear-flow-corpus-rag-release-candidate-20260913.json'); assert.ok(Object.values(manifest.gates).every((value) => value !== 'pending')) })
  it('attaches sanitized desktop, mobile and complete-print evidence', () => { const manifest = JSON.parse(readFileSync(join(root, 'tone-v2/releases/newyear-flow-2.1.0.json'), 'utf8')); assert.equal(manifest.visualEvidence.path, 'tone-v2/evaluations/P04-newyear-flow-visual-render-evidence-20260913.json'); assert.equal(manifest.visualEvidence.sha256, hashFile('../tone-v2/evaluations/P04-newyear-flow-visual-render-evidence-20260913.json')); assert.equal(manifest.visualEvidence.desktop, 'pass_36_of_36'); assert.equal(manifest.visualEvidence.mobile, 'pass_36_of_36'); assert.equal(manifest.visualEvidence.print, 'pass_all_36_sections'); assert.equal(manifest.visualEvidence.containsProviderProse, false) })
})
