import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { getCorpusSnapshot } from '../../src/rag/corpus-registry.js'
import { retrieveRagChunks } from '../../src/rag/retriever.js'
import { buildTemplateSajuReport, reviewGeneratedSajuReportSection, sectionPrompt } from '../../src/report/report-generator.js'
import { analyzeSaju } from '../../src/saju/analyzer.js'
import type { BirthInput, CorpusSnapshot, SajuReportContext } from '../../src/types/index.js'

const root = process.cwd()
const oldPath = 'tone-v2/corpus/pass-angle-service.json'
const newPath = 'tone-v2/corpus/releases/pass-angle-service-2.1.0.json'
const oldMarker = "인성은 교육, 문서, 수양, 학문, 집중력, 자격증처럼 '배워서 확인받는' 영역에 대응한다"
const newMarker = '서버가 계산한 인성은 학습 능력이나 합격 가능성을 증명하지 않는다'
const birth: BirthInput = { year: 1985, month: 3, day: 20, hour: 9, gender: 'male', calendar: 'solar' }
const context: SajuReportContext = { serviceKey: 'pass_angle', concern: '실제 오답 기록과 시험 일정을 기준으로 준비 상태를 확인하고 싶어요.' }
const hashFile = (path: string) => createHash('sha256').update(readFileSync(join(root, 'data', path), 'utf8')).digest('hex')
const hashRootFile = (path: string) => createHash('sha256').update(readFileSync(join(root, path))).digest('hex')
function oldSnapshot(): CorpusSnapshot { const current = getCorpusSnapshot(); return { ...current, registryVersion: 'tone-v2.2.0.12', fingerprint: 'old-pass-angle', activePacks: current.activePacks.map((pack) => pack.id === 'pass-angle-service' ? { ...pack, path: oldPath, version: '2.0.0', contentHash: hashFile(oldPath).slice(0, 16) } : pack) } }

describe('[TASK P05] pass_angle corpus/RAG release candidate', () => {
  it('activates reviewed 2.1.0 and retains 2.0.0', () => { const pack = getCorpusSnapshot().activePacks.find((item) => item.id === 'pass-angle-service'); assert.equal(pack?.version, '2.1.0'); assert.equal(pack?.path, newPath); assert.doesNotThrow(() => readFileSync(join(root, 'data', oldPath))); assert.equal(pack?.contentHash, hashFile(newPath).slice(0, 16)) })
  it('records eight semantic-review passes', () => { const review = JSON.parse(readFileSync(join(root, 'tone-v2/corpus-review/pass-angle-2.1.0.json'), 'utf8')); assert.equal(review.status, 'approved'); assert.equal(review.sourcePath, `data/${newPath}`); assert.equal(review.sourceSha256, hashFile(newPath)); assert.equal(review.sampleOutputsIngested, false); assert.equal(review.blocks.length, 8); assert.deepEqual(review.blocks.map((item: any) => item.id), Array.from({ length: 8 }, (_, index) => `pang-${String(index + 1).padStart(3, '0')}`)); assert.ok(review.blocks.every((block: any) => block.status === 'pass' && Object.values(block.checks).every(Boolean))) })
  it('enforces exam fact, calculation, symbol, numeric and health boundaries', () => { const pack = JSON.parse(readFileSync(join(root, 'data', newPath), 'utf8')); const blocks = pack.knowledgeBlocks; const text = blocks.map((block: any) => [block.condition, block.interpretation, ...block.real_world_pattern, block.risk, block.opportunity, block.advice, block.forbidden_generalization].join(' ')).join(' '); const guidance = blocks.map((block: any) => [block.interpretation, ...block.real_world_pattern, block.opportunity, block.advice].join(' ')).join(' '); assert.equal(blocks.length, 8); assert.ok(blocks.every((block: any) => block.real_world_pattern.every((item: string) => item.startsWith('가상 사례:')))); assert.ok(blocks.every((block: any) => /사용자가 확인한 시험 정보와 실제 학습 기록/.test(block.condition) && /서버 계산값은 상징적 질문/.test(block.condition) && /입력되지 않은 값은 알 수 없음/.test(block.condition))); assert.doesNotMatch(text, /현재 항목과 계산값이 직접 연결될 때만 사용한다/); assert.match(text, /지능|학습 능력/); assert.match(text, /합격|불합격/); assert.match(text, /공식 안내|시험 주관/); assert.match(text, /건강|의료/); assert.doesNotMatch(guidance, /2주|3주|D-30|D-7/); assert.doesNotMatch(guidance, /반드시 합격|이번 시험은 붙는다|인성이 약하면.*학업|관성이 있으면.*집중이 살아난다/) })
  it('separates active and stored retrieval', () => { const analysis = analyzeSaju(birth); const active = retrieveRagChunks('시험 인성 학습 기록 합격 준비', analysis, 20, context); const old = retrieveRagChunks('시험 인성 학습 기록 합격 준비', analysis, 20, context, oldSnapshot()); const activeText = active.map((item) => item.content).join('\n'); const oldText = old.map((item) => item.content).join('\n'); assert.ok(active.some((item) => item.domain === 'pass_angle_service')); assert.ok(old.some((item) => item.domain === 'pass_angle_service')); assert.match(activeText, new RegExp(newMarker)); assert.doesNotMatch(activeText, new RegExp(oldMarker)); assert.match(oldText, new RegExp(oldMarker)); assert.doesNotMatch(oldText, new RegExp(newMarker)) })
  it('fails closed on stored hash mismatch', () => { const snapshot = oldSnapshot(); snapshot.activePacks = snapshot.activePacks.map((pack) => pack.id === 'pass-angle-service' ? { ...pack, contentHash: '0000000000000000' } : pack); assert.throws(() => retrieveRagChunks('시험 인성', analyzeSaju(birth), 20, context, snapshot), /Corpus snapshot hash mismatch: pass-angle-service/) })
  it('builds prompts from stored snapshot', () => { const analysis = analyzeSaju(birth); const section = buildTemplateSajuReport(analysis, birth, context).sections[0]; assert.ok(section); const active = sectionPrompt(analysis, birth, context, section).map((item) => item.content).join('\n'); const old = sectionPrompt(analysis, birth, context, section, [], oldSnapshot()).map((item) => item.content).join('\n'); assert.match(active, new RegExp(newMarker)); assert.doesNotMatch(active, new RegExp(oldMarker)); assert.match(old, new RegExp(oldMarker)); assert.doesNotMatch(old, new RegExp(newMarker)) })
  it('reviews saved prose against stored snapshot', () => { const analysis = analyzeSaju(birth); const section = buildTemplateSajuReport(analysis, birth, context).sections[0]; assert.ok(section); const common = { analysis, birth, context, section, hook: '실제 기록으로 준비 상태를 확인해요.', interpretation: `${oldMarker}.` }; const issue = '코퍼스 문장을 복사하지 말고 현재 질문과 근거에 맞는 새 문장으로 다시 쓰세요.'; assert.ok(!reviewGeneratedSajuReportSection(common).issues.includes(issue)); assert.ok(reviewGeneratedSajuReportSection({ ...common, corpusSnapshot: oldSnapshot() }).issues.includes(issue)) })
  it('binds the fresh corpus-2.1.0 provider evidence to the reversible candidate', () => { const manifest = JSON.parse(readFileSync(join(root, 'tone-v2/releases/pass-angle-2.1.0.json'), 'utf8')); const evidencePath = 'tone-v2/evaluations/P04-pass-angle-2-1-full-outline-generation-20260913.json'; const evidence = JSON.parse(readFileSync(join(root, evidencePath), 'utf8')); assert.equal(manifest.state, 'candidate'); assert.equal(manifest.deployed, false); assert.equal(manifest.serviceKey, 'pass_angle'); assert.equal(manifest.generationEvidence.path, evidencePath); assert.equal(manifest.generationEvidence.recordSha256, evidence.evidence.recordSha256); assert.equal(manifest.generationEvidence.acceptedProseSha256, evidence.evidence.acceptedProseSha256); assert.equal(manifest.generationEvidence.containsProviderProse, false); assert.equal('generationEvidenceReason' in manifest, false); assert.equal(evidence.status, 'pass'); assert.equal(evidence.serviceKey, 'pass_angle'); assert.deepEqual(evidence.completion, { completedSections: 52, expectedSections: 52, recordStatus: 'complete', firstFailure: null, attemptedAfterFailure: 0, attemptedOutsideLimit: 0 }); assert.equal(evidence.corpus.version, '2.1.0'); assert.equal(evidence.corpus.sha256, hashFile(newPath)); assert.deepEqual(evidence.replay.passed, 52); assert.deepEqual(evidence.replay.failed, 0); assert.equal(evidence.evidence.containsProviderProse, false); assert.equal(evidence.evidence.containsSecrets, false); assert.equal(evidence.evidence.containsPersonalData, false); assert.equal(evidence.verification.independentReview, 'approved_codex_review'); assert.deepEqual(manifest.corpus.candidate, { path: `data/${newPath}`, version: '2.1.0', sha256: hashFile(newPath) }); assert.deepEqual(manifest.corpus.previous, { path: `data/${oldPath}`, version: '2.0.0', sha256: hashFile(oldPath) }); assert.equal(manifest.attachment.newReportsOnly, true); assert.equal(manifest.attachment.customerRecordMutation, false); assert.equal(manifest.rollback.strategy, 'registry_only'); assert.equal(manifest.verificationEvidence, 'tone-v2/evaluations/P05-pass-angle-corpus-rag-release-candidate-20260913.json'); assert.equal(manifest.gates.providerOutputEvaluation, 'pass_52_of_52'); assert.ok(Object.values(manifest.gates).every((value) => value !== 'pending')) })
  it('attaches sanitized desktop, mobile and complete-print evidence', () => { const manifest = JSON.parse(readFileSync(join(root, 'tone-v2/releases/pass-angle-2.1.0.json'), 'utf8')); const evidencePath = 'tone-v2/evaluations/P04-pass-angle-visual-render-evidence-20260913.json'; assert.equal(manifest.visualEvidence.path, evidencePath); assert.equal(manifest.visualEvidence.sha256, hashRootFile(evidencePath)); assert.equal(manifest.visualEvidence.desktop, 'pass_52_of_52'); assert.equal(manifest.visualEvidence.mobile, 'pass_52_of_52'); assert.equal(manifest.visualEvidence.print, 'pass_all_52_sections'); assert.equal(manifest.visualEvidence.containsProviderProse, false) })
})
